FROM golang:1.20 AS builder

WORKDIR /src

ADD . .
ARG VERSION
RUN CGO_ENABLED=0 \
    GOOS=linux \
    go build \
    -ldflags="-X main.Version=$VERSION" \
    -o /protoc-gen-go-listify .

FROM scratch
COPY --from=builder /protoc-gen-go-listify /
ENTRYPOINT ["/protoc-gen-go-listify"]
