package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/pentops/protoc-gen-listify/listify/v1"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/pluginpb"
)

const (
	version = "1.0"

	errorPackage   = protogen.GoImportPath("errors")
	fmtPackage     = protogen.GoImportPath("fmt")
	regexpPackage  = protogen.GoImportPath("regexp")
	strconvPackage = protogen.GoImportPath("strconv")
	timePackage    = protogen.GoImportPath("time")

	listifyPackage = protogen.GoImportPath("github.com/pentops/protoc-gen-listify/listify/v1")
)

func main() {
	showVersion := flag.Bool("version", false, "Print the version information and exit")
	flag.Parse()
	if *showVersion {
		fmt.Printf("protoc-gen-listify %v\n", version)
		os.Exit(0)
	}

	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}

			_, err := genFile(gen, f)
			if err != nil {
				return err
			}
		}

		return nil
	})
}

// genFile generates a _listify.pb.go file containing helper methods on services
// requests for generalizing sorting, filtering, searching, and pagination
func genFile(gen *protogen.Plugin, file *protogen.File) (*protogen.GeneratedFile, error) {
	if len(file.Services) == 0 {
		return nil, nil
	}

	filename := file.GeneratedFilenamePrefix + "_listify.pb.go"

	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-listify. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("var (")
	g.P("ErrFilterValidationInvalidField = ", errorPackage.Ident("New"), `("invalid field name(s) for filter")`)
	g.P("ErrFilterValidationInvalidValue = ", errorPackage.Ident("New"), `("invalid value(s) for filter")`)
	g.P()
	g.P(`uuidMatch = `, regexpPackage.Ident("MustCompile"), `("(?i)^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$")`)
	g.P(`dateMatch = `, regexpPackage.Ident("MustCompile"), `("^([0-9]{4}-?([0-9]{2})?-?([0-9]{2})?)$")`)
	g.P(")")
	g.P()

	genTypeValidators(gen, g)

	generated, err := genFileContent(gen, file, g)
	if err != nil {
		return nil, err
	}

	if !generated {
		g.Skip()
		return nil, nil
	}

	return g, nil
}

func genTypeValidators(gen *protogen.Plugin, g *protogen.GeneratedFile) {
	g.P("func Listify_ValidDouble(f *", listifyPackage.Ident("Filter"), ") error{")
	g.P("if f.GetRange() != nil {")
	g.P("return nil")
	g.P("}")
	g.P()
	g.P("s := f.GetValue()")
	g.P("_, err := ", strconvPackage.Ident("ParseFloat"), "(s, 64)")
	g.P("if err != nil {")
	g.P("return ", fmtPackage.Ident("Errorf"), `("%w: %s", ErrFilterValidationInvalidValue, s)`)
	g.P("}")
	g.P()
	g.P("return nil")
	g.P("}")
	g.P()

	g.P("func Listify_ValidFloat(f *", listifyPackage.Ident("Filter"), ") error{")
	g.P("if f.GetRange() != nil {")
	g.P("return nil")
	g.P("}")
	g.P()
	g.P("s := f.GetValue()")
	g.P("_, err := ", strconvPackage.Ident("ParseFloat"), "(s, 32)")
	g.P("if err != nil {")
	g.P("return ", fmtPackage.Ident("Errorf"), `("%w: %s", ErrFilterValidationInvalidValue, s)`)
	g.P("}")
	g.P()
	g.P("return nil")
	g.P("}")
	g.P()

	g.P("func Listify_ValidInt32(f *", listifyPackage.Ident("Filter"), ") error{")
	g.P("if f.GetRange() != nil {")
	g.P("return nil")
	g.P("}")
	g.P()
	g.P("s := f.GetValue()")
	g.P("_, err := ", strconvPackage.Ident("ParseInt"), "(s, 10, 32)")
	g.P("if err != nil {")
	g.P("return ", fmtPackage.Ident("Errorf"), `("%w: %s", ErrFilterValidationInvalidValue, s)`)
	g.P("}")
	g.P()
	g.P("return nil")
	g.P("}")
	g.P()

	g.P("func Listify_ValidInt64(f *", listifyPackage.Ident("Filter"), ") error{")
	g.P("if f.GetRange() != nil {")
	g.P("return nil")
	g.P("}")
	g.P()
	g.P("s := f.GetValue()")
	g.P("_, err := ", strconvPackage.Ident("ParseInt"), "(s, 10, 64)")
	g.P("if err != nil {")
	g.P("return ", fmtPackage.Ident("Errorf"), `("%w: %s", ErrFilterValidationInvalidValue, s)`)
	g.P("}")
	g.P()
	g.P("return nil")
	g.P("}")
	g.P()

	g.P("func Listify_ValidUint32(f *", listifyPackage.Ident("Filter"), ") error{")
	g.P("if f.GetRange() != nil {")
	g.P("return nil")
	g.P("}")
	g.P()
	g.P("s := f.GetValue()")
	g.P("_, err := ", strconvPackage.Ident("ParseUint"), "(s, 10, 32)")
	g.P("if err != nil {")
	g.P("return ", fmtPackage.Ident("Errorf"), `("%w: %s", ErrFilterValidationInvalidValue, s)`)
	g.P("}")
	g.P()
	g.P("return nil")
	g.P("}")
	g.P()

	g.P("func Listify_ValidUint64(f *", listifyPackage.Ident("Filter"), ") error{")
	g.P("if f.GetRange() != nil {")
	g.P("return nil")
	g.P("}")
	g.P()
	g.P("s := f.GetValue()")
	g.P("_, err := ", strconvPackage.Ident("ParseUint"), "(s, 10, 64)")
	g.P("if err != nil {")
	g.P("return ", fmtPackage.Ident("Errorf"), `("%w: %s", ErrFilterValidationInvalidValue, s)`)
	g.P("}")
	g.P()
	g.P("return nil")
	g.P("}")
	g.P()

	g.P("func Listify_ValidBool(f *", listifyPackage.Ident("Filter"), ") error{")
	g.P("if f.GetRange() != nil {")
	g.P("return nil")
	g.P("}")
	g.P()
	g.P("s := f.GetValue()")
	g.P("_, err := ", strconvPackage.Ident("ParseBool"), "(s)")
	g.P("if err != nil {")
	g.P("return ", fmtPackage.Ident("Errorf"), `("%w: %s", ErrFilterValidationInvalidValue, s)`)
	g.P("}")
	g.P("return nil")
	g.P("}")
	g.P()

	g.P("func Listify_ValidUniqueString(f *", listifyPackage.Ident("Filter"), ") error{")
	g.P("if f.GetRange() != nil {")
	g.P("return ", fmtPackage.Ident("Errorf"), `("%w: range", ErrFilterValidationInvalidValue)`)
	g.P("}")
	g.P()
	g.P("return nil")
	g.P("}")
	g.P()

	g.P("func Listify_ValidUUID(f *", listifyPackage.Ident("Filter"), ") error{")
	g.P("if f.GetRange() != nil {")
	g.P("return ", fmtPackage.Ident("Errorf"), `("%w: range", ErrFilterValidationInvalidValue)`)
	g.P("}")
	g.P()
	g.P("if !uuidMatch.MatchString(f.GetValue()) {")
	g.P("return ", fmtPackage.Ident("Errorf"), `("%w: %s", ErrFilterValidationInvalidValue, f.GetValue())`)
	g.P("}")
	g.P()
	g.P("return nil")
	g.P("}")
	g.P()

	g.P("func Listify_ValidDate(f *", listifyPackage.Ident("Filter"), ") error{")
	g.P("if f.GetRange() != nil {")
	g.P("return nil")
	g.P("}")
	g.P()
	g.P("if !dateMatch.MatchString(f.GetValue()) {")
	g.P("return ", fmtPackage.Ident("Errorf"), `("%w: %s", ErrFilterValidationInvalidValue, f.GetValue())`)
	g.P("}")
	g.P()
	g.P("return nil")
	g.P("}")
	g.P()

	g.P("func Listify_ValidTimestamp(f *", listifyPackage.Ident("Filter"), ") error{")
	g.P("if f.GetRange() != nil {")
	g.P("return nil")
	g.P("}")
	g.P()
	g.P("_, err := ", timePackage.Ident("Parse"), "(time.RFC3339, f.GetValue())")
	g.P("if err != nil {")
	g.P("return ", fmtPackage.Ident("Errorf"), `("%w: %s", ErrFilterValidationInvalidValue, f.GetValue())`)
	g.P("}")
	g.P()
	g.P("return nil")
	g.P("}")
	g.P()
}

func genFileContent(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile) (bool, error) {
	for _, service := range file.Services {
		for _, method := range service.Methods {
			// Skip streaming methods
			if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
				continue
			}

			// Only generate for methods with the listify.api option set to true
			methodAnnotations, ok := proto.GetExtension(method.Desc.Options(), listify.E_Api).(*listify.MethodOptions)
			if ok {
				if methodAnnotations == nil || !methodAnnotations.Enable {
					continue
				}
			}

			err := genFilterableContent(gen, method, g)
			if err != nil {
				return false, err
			}
		}
	}

	return true, nil
}

func genFilterableContent(gen *protogen.Plugin, method *protogen.Method, g *protogen.GeneratedFile) error {
	// Generate the ValidateFilters method for the children of the output message
	filterables, err := genFilterables(gen, method.Output, g, true)
	if err != nil {
		return err
	}

	// Generate the ValidateFilters method for the input message
	g.P("func (r *", method.Input.GoIdent.GoName, ") ValidateFilters() error{")
	g.P("validFilters := map[string]func(*", listifyPackage.Ident("Filter"), ")error{")
	for filterable, validFunc := range filterables {
		g.P(`"`, filterable, `": `, validFunc, ",")
	}
	g.P("}")
	g.P()
	g.P("failedFilters := []string{}")
	g.P()
	g.P("for _, filter := range r.Filters {")
	g.P("validator, ok := validFilters[filter.Field]")
	g.P("if !ok {")
	g.P("failedFilters = append(failedFilters, filter.Field)")
	g.P("continue")
	g.P("}")
	g.P()
	g.P("if err := validator(filter); err != nil {")
	g.P("failedFilters = append(failedFilters, filter.Field)")
	g.P("}")
	g.P("}")
	g.P()
	g.P("if len(failedFilters) > 0 {")
	g.P("return ", fmtPackage.Ident("Errorf"), `("%w: %q", ErrFilterValidationInvalidField, failedFilters)`)
	g.P("}")
	g.P()
	g.P("return nil")
	g.P("}")
	g.P()

	return nil
}

func genFilterables(gen *protogen.Plugin, msg *protogen.Message, g *protogen.GeneratedFile, output bool) (map[string]string, error) {
	filterables := map[string]string{}

	for _, field := range msg.Fields {
		fieldAnnotations, ok := proto.GetExtension(field.Desc.Options(), listify.E_Rules).(*listify.FieldRulesOptions)
		if ok && fieldAnnotations != nil {
			switch field.Desc.Kind().String() {
			case "double":
				if fieldAnnotations.GetDouble() != nil && fieldAnnotations.GetDouble().Filterable {
					filterables[field.Desc.TextName()] = "Listify_ValidDouble"
				}
			case "float":
				if fieldAnnotations.GetFloat() != nil && fieldAnnotations.GetFloat().Filterable {
					filterables[field.Desc.TextName()] = "Listify_ValidFloat"
				}
			case "int32", "sint32", "sfixed32":
				if fieldAnnotations.GetInt32() != nil && fieldAnnotations.GetInt32().Filterable {
					filterables[field.Desc.TextName()] = "Listify_ValidInt32"
				}
			case "int64", "sint64", "sfixed64":
				if fieldAnnotations.GetInt64() != nil && fieldAnnotations.GetInt64().Filterable {
					filterables[field.Desc.TextName()] = "Listify_ValidInt64"
				}
			case "uint32", "fixed32":
				if fieldAnnotations.GetUint32() != nil && fieldAnnotations.GetUint32().Filterable {
					filterables[field.Desc.TextName()] = "Listify_ValidUint32"
				}
			case "uint64", "fixed64":
				if fieldAnnotations.GetUint64() != nil && fieldAnnotations.GetUint64().Filterable {
					filterables[field.Desc.TextName()] = "Listify_ValidUint64"
				}
			case "bool":
				if fieldAnnotations.GetBool() != nil && fieldAnnotations.GetBool().Filterable {
					filterables[field.Desc.TextName()] = "Listify_ValidBool"
				}
			case "enum":
				if fieldAnnotations.GetEnum() != nil && fieldAnnotations.GetEnum().Filterable {
					valids := map[string]struct{}{}
					for _, v := range field.Enum.Values {
						valids[string(v.Desc.Name())] = struct{}{}
					}

					g.P("func ", msg.GoIdent.GoName, "_Valid", field.GoName, "(f *", listifyPackage.Ident("Filter"), ") error{")
					g.P("if f.GetRange() != nil {")
					g.P("return ", fmtPackage.Ident("Errorf"), `("%w: range", ErrFilterValidationInvalidValue)`)
					g.P("}")
					g.P()
					g.P("switch f.GetValue() {")
					for v := range valids {
						g.P("case \"", v, "\":")
						g.P("return nil")
					}
					g.P("}")
					g.P()
					g.P("return ", fmtPackage.Ident("Errorf"), `("%w: %s", ErrFilterValidationInvalidValue, f.GetValue())`)
					g.P("}")
					g.P()

					filterables[field.Desc.TextName()] = fmt.Sprintf("%s_Valid%s", msg.GoIdent.GoName, field.GoName)
				}
			case "string":
				if fieldAnnotations.GetString_() != nil {
					if fieldAnnotations.GetString_().GetForeignKey() != nil {
						if fieldAnnotations.GetString_().GetForeignKey().GetUniqueString() != nil &&
							fieldAnnotations.GetString_().GetForeignKey().GetUniqueString().Filterable {
							filterables[field.Desc.TextName()] = "Listify_ValidUniqueString"
						}

						if fieldAnnotations.GetString_().GetForeignKey().GetUuid() != nil &&
							fieldAnnotations.GetString_().GetForeignKey().GetUuid().Filterable {
							filterables[field.Desc.TextName()] = "Listify_ValidUUID"
						}
					}

					if fieldAnnotations.GetString_().GetDate() != nil && fieldAnnotations.GetString_().GetDate().Filterable {
						filterables[field.Desc.TextName()] = "Listify_ValidDate"
					}
				}
			case "message":
				if field.Desc.Message().FullName() == "google.protobuf.Timestamp" {
					if fieldAnnotations.GetTimestamp() != nil && fieldAnnotations.GetTimestamp().Filterable {
						filterables[field.Desc.TextName()] = "Listify_ValidTimestamp"
					}
				}
			}
		}

		if field.Message != nil {
			nested, err := genFilterables(gen, field.Message, g, false)
			if err != nil {
				return filterables, err
			}

			for k, v := range nested {
				filterables[k] = v
			}
		}
	}

	for _, oneof := range msg.Oneofs {
		oneofAnnotations, ok := proto.GetExtension(oneof.Desc.Options(), listify.E_OneofRules).(*listify.OneofRulesOptions)
		if ok && oneofAnnotations != nil {
			if oneofAnnotations.Filterable {
				valids := map[string]struct{}{}
				for _, v := range oneof.Fields {
					valids[string(v.Desc.Message().Name())] = struct{}{}
				}

				g.P("func ", msg.GoIdent.GoName, "_Valid", oneof.GoName, "(f *", listifyPackage.Ident("Filter"), ") error{")
				g.P("if f.GetRange() != nil {")
				g.P("return ", fmtPackage.Ident("Errorf"), `("%w: range", ErrFilterValidationInvalidValue)`)
				g.P("}")
				g.P()
				g.P("switch f.GetValue() {")
				for v := range valids {
					g.P("case \"", v, "\":")
					g.P("return nil")
				}
				g.P("}")
				g.P()
				g.P("return ", fmtPackage.Ident("Errorf"), `("%w: %s", ErrFilterValidationInvalidValue, f.GetValue())`)
				g.P("}")
				g.P()

				filterables[string(oneof.Desc.Name())] = fmt.Sprintf("%s_Valid%s", msg.GoIdent.GoName, oneof.GoName)
			}
		}
	}

	if len(filterables) > 0 && !output {
		genValidateFiltersMethod(gen, msg, g, filterables)
	}

	return filterables, nil
}

func genValidateFiltersMethod(gen *protogen.Plugin, msg *protogen.Message, g *protogen.GeneratedFile, filterables map[string]string) {
	g.P("func (r *", msg.GoIdent.GoName, ") ValidateFilters(filters []*", listifyPackage.Ident("Filter"), ") error{")
	g.P("validFilters := map[string]func(*", listifyPackage.Ident("Filter"), ")error{")
	for filterable, validFunc := range filterables {
		g.P(`"`, filterable, `": `, validFunc, ",")
	}
	g.P("}")
	g.P()
	g.P("failedFilters := []string{}")
	g.P()
	g.P("for _, filter := range filters {")
	g.P("validator, ok := validFilters[filter.Field]")
	g.P("if !ok {")
	g.P("failedFilters = append(failedFilters, filter.Field)")
	g.P("continue")
	g.P("}")
	g.P()
	g.P("if err := validator(filter); err != nil {")
	g.P("failedFilters = append(failedFilters, filter.Field)")
	g.P("}")
	g.P("}")
	g.P()
	g.P("if len(failedFilters) > 0 {")
	g.P("return ", fmtPackage.Ident("Errorf"), `("%w: %q", ErrFilterValidationInvalidField, failedFilters)`)
	g.P("}")
	g.P()
	g.P("return nil")
	g.P("}")
	g.P()
}
