// Code generated by protoc-gen-listify. DO NOT EDIT.

package sspb

import (
	errors "errors"
	fmt "fmt"
	v1 "github.com/pentops/protoc-gen-listify/listify/v1"
	regexp "regexp"
	strconv "strconv"
	time "time"
)

var (
	ErrFilterValidationInvalidField              = errors.New("invalid field name(s) for filter")
	ErrFilterValidationInvalidRangeMinMaxMissing = errors.New("invalid range min and/or max must be provided")
	ErrFilterValidationInvalidRangeMinMax        = errors.New("invalid range min/max")
	ErrFilterValidationInvalidRangeType          = errors.New("invalid type for range")
	ErrFilterValidationInvalidValue              = errors.New("invalid value(s) for filter")

	uuidMatch = regexp.MustCompile("(?i)^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$")
	dateMatch = regexp.MustCompile("^([0-9]{4}-?([0-9]{2})?-?([0-9]{2})?)$")
)

func ListifyFilter_ValidDouble(f *v1.Filter) error {
	if f.GetRange() != nil {
		r := f.GetRange().GetDouble()
		if r == nil {
			return fmt.Errorf("%w: expected double", ErrFilterValidationInvalidRangeType)
		}

		if r.Min == nil && r.Max == nil {
			return ErrFilterValidationInvalidRangeMinMaxMissing
		}

		if r.Min != nil && r.Max != nil && r.Min.Value > r.Max.Value {
			return ErrFilterValidationInvalidRangeMinMax
		}

		return nil
	}

	s := f.GetValue()
	_, err := strconv.ParseFloat(s, 64)
	if err != nil {
		return fmt.Errorf("%w: %s", ErrFilterValidationInvalidValue, s)
	}

	return nil
}

func ListifyFilter_ValidFloat(f *v1.Filter) error {
	if f.GetRange() != nil {
		r := f.GetRange().GetFloat()
		if r == nil {
			return fmt.Errorf("%w: expected float", ErrFilterValidationInvalidRangeType)
		}

		if r.Min == nil && r.Max == nil {
			return ErrFilterValidationInvalidRangeMinMaxMissing
		}

		if r.Min != nil && r.Max != nil && r.Min.Value > r.Max.Value {
			return ErrFilterValidationInvalidRangeMinMax
		}

		return nil
	}

	s := f.GetValue()
	_, err := strconv.ParseFloat(s, 32)
	if err != nil {
		return fmt.Errorf("%w: %s", ErrFilterValidationInvalidValue, s)
	}

	return nil
}

func ListifyFilter_ValidInt32(f *v1.Filter) error {
	if f.GetRange() != nil {
		r := f.GetRange().GetInt32()
		if r == nil {
			return fmt.Errorf("%w: expected int32", ErrFilterValidationInvalidRangeType)
		}

		if r.Min == nil && r.Max == nil {
			return ErrFilterValidationInvalidRangeMinMaxMissing
		}

		if r.Min != nil && r.Max != nil && r.Min.Value > r.Max.Value {
			return ErrFilterValidationInvalidRangeMinMax
		}

		return nil
	}

	s := f.GetValue()
	_, err := strconv.ParseInt(s, 10, 32)
	if err != nil {
		return fmt.Errorf("%w: %s", ErrFilterValidationInvalidValue, s)
	}

	return nil
}

func ListifyFilter_ValidSint32(f *v1.Filter) error {
	if f.GetRange() != nil {
		r := f.GetRange().GetSint32()
		if r == nil {
			return fmt.Errorf("%w: expected sint32", ErrFilterValidationInvalidRangeType)
		}

		if r.Min == nil && r.Max == nil {
			return ErrFilterValidationInvalidRangeMinMaxMissing
		}

		if r.Min != nil && r.Max != nil && r.Min.Value > r.Max.Value {
			return ErrFilterValidationInvalidRangeMinMax
		}

		return nil
	}

	s := f.GetValue()
	_, err := strconv.ParseInt(s, 10, 32)
	if err != nil {
		return fmt.Errorf("%w: %s", ErrFilterValidationInvalidValue, s)
	}

	return nil
}

func ListifyFilter_ValidSfixed32(f *v1.Filter) error {
	if f.GetRange() != nil {
		r := f.GetRange().GetSfixed32()
		if r == nil {
			return fmt.Errorf("%w: expected sfixed32", ErrFilterValidationInvalidRangeType)
		}

		if r.Min == nil && r.Max == nil {
			return ErrFilterValidationInvalidRangeMinMaxMissing
		}

		if r.Min != nil && r.Max != nil && r.Min.Value > r.Max.Value {
			return ErrFilterValidationInvalidRangeMinMax
		}

		return nil
	}

	s := f.GetValue()
	_, err := strconv.ParseInt(s, 10, 32)
	if err != nil {
		return fmt.Errorf("%w: %s", ErrFilterValidationInvalidValue, s)
	}

	return nil
}

func ListifyFilter_ValidInt64(f *v1.Filter) error {
	if f.GetRange() != nil {
		r := f.GetRange().GetInt64()
		if r == nil {
			return fmt.Errorf("%w: expected int64", ErrFilterValidationInvalidRangeType)
		}

		if r.Min == nil && r.Max == nil {
			return ErrFilterValidationInvalidRangeMinMaxMissing
		}

		if r.Min != nil && r.Max != nil && r.Min.Value > r.Max.Value {
			return ErrFilterValidationInvalidRangeMinMax
		}

		return nil
	}

	s := f.GetValue()
	_, err := strconv.ParseInt(s, 10, 64)
	if err != nil {
		return fmt.Errorf("%w: %s", ErrFilterValidationInvalidValue, s)
	}

	return nil
}

func ListifyFilter_ValidSint64(f *v1.Filter) error {
	if f.GetRange() != nil {
		r := f.GetRange().GetSint64()
		if r == nil {
			return fmt.Errorf("%w: expected sint64", ErrFilterValidationInvalidRangeType)
		}

		if r.Min == nil && r.Max == nil {
			return ErrFilterValidationInvalidRangeMinMaxMissing
		}

		if r.Min != nil && r.Max != nil && r.Min.Value > r.Max.Value {
			return ErrFilterValidationInvalidRangeMinMax
		}

		return nil
	}

	s := f.GetValue()
	_, err := strconv.ParseInt(s, 10, 64)
	if err != nil {
		return fmt.Errorf("%w: %s", ErrFilterValidationInvalidValue, s)
	}

	return nil
}

func ListifyFilter_ValidSfixed64(f *v1.Filter) error {
	if f.GetRange() != nil {
		r := f.GetRange().GetSfixed64()
		if r == nil {
			return fmt.Errorf("%w: expected sfixed64", ErrFilterValidationInvalidRangeType)
		}

		if r.Min == nil && r.Max == nil {
			return ErrFilterValidationInvalidRangeMinMaxMissing
		}

		if r.Min != nil && r.Max != nil && r.Min.Value > r.Max.Value {
			return ErrFilterValidationInvalidRangeMinMax
		}

		return nil
	}

	s := f.GetValue()
	_, err := strconv.ParseInt(s, 10, 64)
	if err != nil {
		return fmt.Errorf("%w: %s", ErrFilterValidationInvalidValue, s)
	}

	return nil
}

func ListifyFilter_ValidUint32(f *v1.Filter) error {
	if f.GetRange() != nil {
		r := f.GetRange().GetUint32()
		if r == nil {
			return fmt.Errorf("%w: expected uint32", ErrFilterValidationInvalidRangeType)
		}

		if r.Min == nil && r.Max == nil {
			return ErrFilterValidationInvalidRangeMinMaxMissing
		}

		if r.Min != nil && r.Max != nil && r.Min.Value > r.Max.Value {
			return ErrFilterValidationInvalidRangeMinMax
		}

		return nil
	}

	s := f.GetValue()
	_, err := strconv.ParseUint(s, 10, 32)
	if err != nil {
		return fmt.Errorf("%w: %s", ErrFilterValidationInvalidValue, s)
	}

	return nil
}

func ListifyFilter_ValidFixed32(f *v1.Filter) error {
	if f.GetRange() != nil {
		r := f.GetRange().GetFixed32()
		if r == nil {
			return fmt.Errorf("%w: expected fixed32", ErrFilterValidationInvalidRangeType)
		}

		if r.Min == nil && r.Max == nil {
			return ErrFilterValidationInvalidRangeMinMaxMissing
		}

		if r.Min != nil && r.Max != nil && r.Min.Value > r.Max.Value {
			return ErrFilterValidationInvalidRangeMinMax
		}

		return nil
	}

	s := f.GetValue()
	_, err := strconv.ParseUint(s, 10, 32)
	if err != nil {
		return fmt.Errorf("%w: %s", ErrFilterValidationInvalidValue, s)
	}

	return nil
}

func ListifyFilter_ValidUint64(f *v1.Filter) error {
	if f.GetRange() != nil {
		r := f.GetRange().GetUint64()
		if r == nil {
			return fmt.Errorf("%w: expected uint64", ErrFilterValidationInvalidRangeType)
		}

		if r.Min == nil && r.Max == nil {
			return ErrFilterValidationInvalidRangeMinMaxMissing
		}

		if r.Min != nil && r.Max != nil && r.Min.Value > r.Max.Value {
			return ErrFilterValidationInvalidRangeMinMax
		}

		return nil
	}

	s := f.GetValue()
	_, err := strconv.ParseUint(s, 10, 64)
	if err != nil {
		return fmt.Errorf("%w: %s", ErrFilterValidationInvalidValue, s)
	}

	return nil
}

func ListifyFilter_ValidFixed64(f *v1.Filter) error {
	if f.GetRange() != nil {
		r := f.GetRange().GetFixed64()
		if r == nil {
			return fmt.Errorf("%w: expected fixed64", ErrFilterValidationInvalidRangeType)
		}

		if r.Min == nil && r.Max == nil {
			return ErrFilterValidationInvalidRangeMinMaxMissing
		}

		if r.Min != nil && r.Max != nil && r.Min.Value > r.Max.Value {
			return ErrFilterValidationInvalidRangeMinMax
		}

		return nil
	}

	s := f.GetValue()
	_, err := strconv.ParseUint(s, 10, 64)
	if err != nil {
		return fmt.Errorf("%w: %s", ErrFilterValidationInvalidValue, s)
	}

	return nil
}

func ListifyFilter_ValidBool(f *v1.Filter) error {
	if f.GetRange() != nil {
		return fmt.Errorf("%w: range", ErrFilterValidationInvalidValue)
	}

	s := f.GetValue()
	_, err := strconv.ParseBool(s)
	if err != nil {
		return fmt.Errorf("%w: %s", ErrFilterValidationInvalidValue, s)
	}
	return nil
}

func ListifyFilter_ValidUniqueString(f *v1.Filter) error {
	if f.GetRange() != nil {
		return fmt.Errorf("%w: range", ErrFilterValidationInvalidValue)
	}

	return nil
}

func ListifyFilter_ValidUUID(f *v1.Filter) error {
	if f.GetRange() != nil {
		return fmt.Errorf("%w: range", ErrFilterValidationInvalidValue)
	}

	if !uuidMatch.MatchString(f.GetValue()) {
		return fmt.Errorf("%w: %s", ErrFilterValidationInvalidValue, f.GetValue())
	}

	return nil
}

func ListifyFilter_ValidDate(f *v1.Filter) error {
	if f.GetRange() != nil {
		r := f.GetRange().GetDate()
		if r == nil {
			return fmt.Errorf("%w: expected date", ErrFilterValidationInvalidRangeType)
		}

		if r.Min == nil && r.Max == nil {
			return ErrFilterValidationInvalidRangeMinMaxMissing
		}

		return nil
	}

	if !dateMatch.MatchString(f.GetValue()) {
		return fmt.Errorf("%w: %s", ErrFilterValidationInvalidValue, f.GetValue())
	}

	return nil
}

func ListifyFilter_ValidTimestamp(f *v1.Filter) error {
	if f.GetRange() != nil {
		r := f.GetRange().GetTimestamp()
		if r == nil {
			return fmt.Errorf("%w: expected timestamp", ErrFilterValidationInvalidRangeType)
		}

		if r.Min == nil && r.Max == nil {
			return ErrFilterValidationInvalidRangeMinMaxMissing
		}

		if r.Min != nil && r.Max != nil && r.Min.AsTime().After(r.Max.AsTime()) {
			return ErrFilterValidationInvalidRangeMinMax
		}

		return nil
	}

	_, err := time.Parse(time.RFC3339, f.GetValue())
	if err != nil {
		return fmt.Errorf("%w: %s", ErrFilterValidationInvalidValue, f.GetValue())
	}

	return nil
}

func (r *SquareWidget) ValidateFilters(filters []*v1.Filter) error {
	validFilters := map[string]func(*v1.Filter) error{
		"width":  ListifyFilter_ValidInt64,
		"height": ListifyFilter_ValidInt64,
	}

	failedFilters := []string{}

	for _, filter := range filters {
		validator, ok := validFilters[filter.Field]
		if !ok {
			failedFilters = append(failedFilters, filter.Field)
			continue
		}

		if err := validator(filter); err != nil {
			failedFilters = append(failedFilters, filter.Field)
		}
	}

	if len(failedFilters) > 0 {
		return fmt.Errorf("%w: %q", ErrFilterValidationInvalidField, failedFilters)
	}

	return nil
}

func (r *RoundWidget) ValidateFilters(filters []*v1.Filter) error {
	validFilters := map[string]func(*v1.Filter) error{
		"diameter": ListifyFilter_ValidInt64,
	}

	failedFilters := []string{}

	for _, filter := range filters {
		validator, ok := validFilters[filter.Field]
		if !ok {
			failedFilters = append(failedFilters, filter.Field)
			continue
		}

		if err := validator(filter); err != nil {
			failedFilters = append(failedFilters, filter.Field)
		}
	}

	if len(failedFilters) > 0 {
		return fmt.Errorf("%w: %q", ErrFilterValidationInvalidField, failedFilters)
	}

	return nil
}

func WidgetDetails_ValidType(f *v1.Filter) error {
	if f.GetRange() != nil {
		return fmt.Errorf("%w: range", ErrFilterValidationInvalidValue)
	}

	switch f.GetValue() {
	case "SquareWidget":
		return nil
	case "RoundWidget":
		return nil
	}

	return fmt.Errorf("%w: %s", ErrFilterValidationInvalidValue, f.GetValue())
}

func (r *WidgetDetails) ValidateFilters(filters []*v1.Filter) error {
	validFilters := map[string]func(*v1.Filter) error{
		"width":    ListifyFilter_ValidInt64,
		"height":   ListifyFilter_ValidInt64,
		"diameter": ListifyFilter_ValidInt64,
		"type":     WidgetDetails_ValidType,
		"weight":   ListifyFilter_ValidInt64,
		"special":  ListifyFilter_ValidBool,
	}

	failedFilters := []string{}

	for _, filter := range filters {
		validator, ok := validFilters[filter.Field]
		if !ok {
			failedFilters = append(failedFilters, filter.Field)
			continue
		}

		if err := validator(filter); err != nil {
			failedFilters = append(failedFilters, filter.Field)
		}
	}

	if len(failedFilters) > 0 {
		return fmt.Errorf("%w: %q", ErrFilterValidationInvalidField, failedFilters)
	}

	return nil
}

func Widget_ValidStatus(f *v1.Filter) error {
	if f.GetRange() != nil {
		return fmt.Errorf("%w: range", ErrFilterValidationInvalidValue)
	}

	switch f.GetValue() {
	case "WIDGET_STATUS_UNSPECIFIED":
		return nil
	case "WIDGET_STATUS_REQUESTED":
		return nil
	case "WIDGET_STATUS_CREATED":
		return nil
	}

	return fmt.Errorf("%w: %s", ErrFilterValidationInvalidValue, f.GetValue())
}

func (r *Widget) ValidateFilters(filters []*v1.Filter) error {
	validFilters := map[string]func(*v1.Filter) error{
		"customer_id": ListifyFilter_ValidUUID,
		"type":        WidgetDetails_ValidType,
		"weight":      ListifyFilter_ValidInt64,
		"width":       ListifyFilter_ValidInt64,
		"created":     ListifyFilter_ValidTimestamp,
		"special":     ListifyFilter_ValidBool,
		"height":      ListifyFilter_ValidInt64,
		"diameter":    ListifyFilter_ValidInt64,
		"status":      Widget_ValidStatus,
	}

	failedFilters := []string{}

	for _, filter := range filters {
		validator, ok := validFilters[filter.Field]
		if !ok {
			failedFilters = append(failedFilters, filter.Field)
			continue
		}

		if err := validator(filter); err != nil {
			failedFilters = append(failedFilters, filter.Field)
		}
	}

	if len(failedFilters) > 0 {
		return fmt.Errorf("%w: %q", ErrFilterValidationInvalidField, failedFilters)
	}

	return nil
}

func (r *ListWidgetsRequest) ValidateFilters() error {
	validFilters := map[string]func(*v1.Filter) error{
		"width":       ListifyFilter_ValidInt64,
		"created":     ListifyFilter_ValidTimestamp,
		"diameter":    ListifyFilter_ValidInt64,
		"customer_id": ListifyFilter_ValidUUID,
		"type":        WidgetDetails_ValidType,
		"weight":      ListifyFilter_ValidInt64,
		"status":      Widget_ValidStatus,
		"special":     ListifyFilter_ValidBool,
		"height":      ListifyFilter_ValidInt64,
	}

	failedFilters := []string{}

	for _, filter := range r.Filters {
		validator, ok := validFilters[filter.Field]
		if !ok {
			failedFilters = append(failedFilters, filter.Field)
			continue
		}

		if err := validator(filter); err != nil {
			failedFilters = append(failedFilters, filter.Field)
		}
	}

	if len(failedFilters) > 0 {
		return fmt.Errorf("%w: %q", ErrFilterValidationInvalidField, failedFilters)
	}

	return nil
}

func (r *ListWidgetsRequest) GetFilterClauses() *v1.FilterClauses {
	resp := &v1.FilterClauses{}

	for _, filter := range r.Filters {
		clause := &v1.FilterClause{}

		if filter.GetRange() != nil {
			switch k := filter.GetRange().GetType().(type) {
			case *v1.Range_Double:
				if k.Double.Min != nil && k.Double.Max != nil {
					clause.Predicate = fmt.Sprintf(`%s >= ? AND %s <= ?`, filter.Field, filter.Field)
					arg1 := &v1.FilterArgument{Kind: &v1.FilterArgument_Double{Double: k.Double.Min.Value}}
					arg2 := &v1.FilterArgument{Kind: &v1.FilterArgument_Double{Double: k.Double.Max.Value}}
					clause.Arguments = append(clause.Arguments, arg1, arg2)
				} else {
					if k.Double.Min != nil {
						clause.Predicate = fmt.Sprintf(`%s >= ?`, filter.Field)
						clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_Double{Double: k.Double.Min.Value}})
					}
					if k.Double.Max != nil {
						clause.Predicate = fmt.Sprintf(`%s <= ?`, filter.Field)
						clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_Double{Double: k.Double.Max.Value}})
					}
				}
			case *v1.Range_Fixed32:
				if k.Fixed32.Min != nil && k.Fixed32.Max != nil {
					clause.Predicate = fmt.Sprintf(`%s >= ? AND %s <= ?`, filter.Field, filter.Field)
					arg1 := &v1.FilterArgument{Kind: &v1.FilterArgument_Fixed32{Fixed32: k.Fixed32.Min.Value}}
					arg2 := &v1.FilterArgument{Kind: &v1.FilterArgument_Fixed32{Fixed32: k.Fixed32.Max.Value}}
					clause.Arguments = append(clause.Arguments, arg1, arg2)
				} else {
					if k.Fixed32.Min != nil {
						clause.Predicate = fmt.Sprintf(`%s >= ?`, filter.Field)
						clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_Fixed32{Fixed32: k.Fixed32.Min.Value}})
					}
					if k.Fixed32.Max != nil {
						clause.Predicate = fmt.Sprintf(`%s <= ?`, filter.Field)
						clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_Fixed32{Fixed32: k.Fixed32.Max.Value}})
					}
				}
			case *v1.Range_Fixed64:
				if k.Fixed64.Min != nil && k.Fixed64.Max != nil {
					clause.Predicate = fmt.Sprintf(`%s >= ? AND %s <= ?`, filter.Field, filter.Field)
					arg1 := &v1.FilterArgument{Kind: &v1.FilterArgument_Fixed64{Fixed64: k.Fixed64.Min.Value}}
					arg2 := &v1.FilterArgument{Kind: &v1.FilterArgument_Fixed64{Fixed64: k.Fixed64.Max.Value}}
					clause.Arguments = append(clause.Arguments, arg1, arg2)
				} else {
					if k.Fixed64.Min != nil {
						clause.Predicate = fmt.Sprintf(`%s >= ?`, filter.Field)
						clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_Fixed64{Fixed64: k.Fixed64.Min.Value}})
					}
					if k.Fixed64.Max != nil {
						clause.Predicate = fmt.Sprintf(`%s <= ?`, filter.Field)
						clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_Fixed64{Fixed64: k.Fixed64.Max.Value}})
					}
				}
			case *v1.Range_Float:
				if k.Float.Min != nil && k.Float.Max != nil {
					clause.Predicate = fmt.Sprintf(`%s >= ? AND %s <= ?`, filter.Field, filter.Field)
					arg1 := &v1.FilterArgument{Kind: &v1.FilterArgument_Float{Float: k.Float.Min.Value}}
					arg2 := &v1.FilterArgument{Kind: &v1.FilterArgument_Float{Float: k.Float.Max.Value}}
					clause.Arguments = append(clause.Arguments, arg1, arg2)
				} else {
					if k.Float.Min != nil {
						clause.Predicate = fmt.Sprintf(`%s >= ?`, filter.Field)
						clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_Float{Float: k.Float.Min.Value}})
					}
					if k.Float.Max != nil {
						clause.Predicate = fmt.Sprintf(`%s <= ?`, filter.Field)
						clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_Float{Float: k.Float.Max.Value}})
					}
				}
			case *v1.Range_Int32:
				if k.Int32.Min != nil && k.Int32.Max != nil {
					clause.Predicate = fmt.Sprintf(`%s >= ? AND %s <= ?`, filter.Field, filter.Field)
					arg1 := &v1.FilterArgument{Kind: &v1.FilterArgument_Int32{Int32: k.Int32.Min.Value}}
					arg2 := &v1.FilterArgument{Kind: &v1.FilterArgument_Int32{Int32: k.Int32.Max.Value}}
					clause.Arguments = append(clause.Arguments, arg1, arg2)
				} else {
					if k.Int32.Min != nil {
						clause.Predicate = fmt.Sprintf(`%s >= ?`, filter.Field)
						clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_Int32{Int32: k.Int32.Min.Value}})
					}
					if k.Int32.Max != nil {
						clause.Predicate = fmt.Sprintf(`%s <= ?`, filter.Field)
						clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_Int32{Int32: k.Int32.Max.Value}})
					}
				}
			case *v1.Range_Int64:
				if k.Int64.Min != nil && k.Int64.Max != nil {
					clause.Predicate = fmt.Sprintf(`%s >= ? AND %s <= ?`, filter.Field, filter.Field)
					arg1 := &v1.FilterArgument{Kind: &v1.FilterArgument_Int64{Int64: k.Int64.Min.Value}}
					arg2 := &v1.FilterArgument{Kind: &v1.FilterArgument_Int64{Int64: k.Int64.Max.Value}}
					clause.Arguments = append(clause.Arguments, arg1, arg2)
				} else {
					if k.Int64.Min != nil {
						clause.Predicate = fmt.Sprintf(`%s >= ?`, filter.Field)
						clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_Int64{Int64: k.Int64.Min.Value}})
					}
					if k.Int64.Max != nil {
						clause.Predicate = fmt.Sprintf(`%s <= ?`, filter.Field)
						clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_Int64{Int64: k.Int64.Max.Value}})
					}
				}
			case *v1.Range_Sfixed32:
				if k.Sfixed32.Min != nil && k.Sfixed32.Max != nil {
					clause.Predicate = fmt.Sprintf(`%s >= ? AND %s <= ?`, filter.Field, filter.Field)
					arg1 := &v1.FilterArgument{Kind: &v1.FilterArgument_Sfixed32{Sfixed32: k.Sfixed32.Min.Value}}
					arg2 := &v1.FilterArgument{Kind: &v1.FilterArgument_Sfixed32{Sfixed32: k.Sfixed32.Max.Value}}
					clause.Arguments = append(clause.Arguments, arg1, arg2)
				} else {
					if k.Sfixed32.Min != nil {
						clause.Predicate = fmt.Sprintf(`%s >= ?`, filter.Field)
						clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_Sfixed32{Sfixed32: k.Sfixed32.Min.Value}})
					}
					if k.Sfixed32.Max != nil {
						clause.Predicate = fmt.Sprintf(`%s <= ?`, filter.Field)
						clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_Sfixed32{Sfixed32: k.Sfixed32.Max.Value}})
					}
				}
			case *v1.Range_Sfixed64:
				if k.Sfixed64.Min != nil && k.Sfixed64.Max != nil {
					clause.Predicate = fmt.Sprintf(`%s >= ? AND %s <= ?`, filter.Field, filter.Field)
					arg1 := &v1.FilterArgument{Kind: &v1.FilterArgument_Sfixed64{Sfixed64: k.Sfixed64.Min.Value}}
					arg2 := &v1.FilterArgument{Kind: &v1.FilterArgument_Sfixed64{Sfixed64: k.Sfixed64.Max.Value}}
					clause.Arguments = append(clause.Arguments, arg1, arg2)
				} else {
					if k.Sfixed64.Min != nil {
						clause.Predicate = fmt.Sprintf(`%s >= ?`, filter.Field)
						clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_Sfixed64{Sfixed64: k.Sfixed64.Min.Value}})
					}
					if k.Sfixed64.Max != nil {
						clause.Predicate = fmt.Sprintf(`%s <= ?`, filter.Field)
						clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_Sfixed64{Sfixed64: k.Sfixed64.Max.Value}})
					}
				}
			case *v1.Range_Sint32:
				if k.Sint32.Min != nil && k.Sint32.Max != nil {
					clause.Predicate = fmt.Sprintf(`%s >= ? AND %s <= ?`, filter.Field, filter.Field)
					arg1 := &v1.FilterArgument{Kind: &v1.FilterArgument_Sint32{Sint32: k.Sint32.Min.Value}}
					arg2 := &v1.FilterArgument{Kind: &v1.FilterArgument_Sint32{Sint32: k.Sint32.Max.Value}}
					clause.Arguments = append(clause.Arguments, arg1, arg2)
				} else {
					if k.Sint32.Min != nil {
						clause.Predicate = fmt.Sprintf(`%s >= ?`, filter.Field)
						clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_Sint32{Sint32: k.Sint32.Min.Value}})
					}
					if k.Sint32.Max != nil {
						clause.Predicate = fmt.Sprintf(`%s <= ?`, filter.Field)
						clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_Sint32{Sint32: k.Sint32.Max.Value}})
					}
				}
			case *v1.Range_Sint64:
				if k.Sint64.Min != nil && k.Sint64.Max != nil {
					clause.Predicate = fmt.Sprintf(`%s >= ? AND %s <= ?`, filter.Field, filter.Field)
					arg1 := &v1.FilterArgument{Kind: &v1.FilterArgument_Sint64{Sint64: k.Sint64.Min.Value}}
					arg2 := &v1.FilterArgument{Kind: &v1.FilterArgument_Sint64{Sint64: k.Sint64.Max.Value}}
					clause.Arguments = append(clause.Arguments, arg1, arg2)
				} else {
					if k.Sint64.Min != nil {
						clause.Predicate = fmt.Sprintf(`%s >= ?`, filter.Field)
						clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_Sint64{Sint64: k.Sint64.Min.Value}})
					}
					if k.Sint64.Max != nil {
						clause.Predicate = fmt.Sprintf(`%s <= ?`, filter.Field)
						clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_Sint64{Sint64: k.Sint64.Max.Value}})
					}
				}
			case *v1.Range_Uint32:
				if k.Uint32.Min != nil && k.Uint32.Max != nil {
					clause.Predicate = fmt.Sprintf(`%s >= ? AND %s <= ?`, filter.Field, filter.Field)
					arg1 := &v1.FilterArgument{Kind: &v1.FilterArgument_Uint32{Uint32: k.Uint32.Min.Value}}
					arg2 := &v1.FilterArgument{Kind: &v1.FilterArgument_Uint32{Uint32: k.Uint32.Max.Value}}
					clause.Arguments = append(clause.Arguments, arg1, arg2)
				} else {
					if k.Uint32.Min != nil {
						clause.Predicate = fmt.Sprintf(`%s >= ?`, filter.Field)
						clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_Uint32{Uint32: k.Uint32.Min.Value}})
					}
					if k.Uint32.Max != nil {
						clause.Predicate = fmt.Sprintf(`%s <= ?`, filter.Field)
						clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_Uint32{Uint32: k.Uint32.Max.Value}})
					}
				}
			case *v1.Range_Uint64:
				if k.Uint64.Min != nil && k.Uint64.Max != nil {
					clause.Predicate = fmt.Sprintf(`%s >= ? AND %s <= ?`, filter.Field, filter.Field)
					arg1 := &v1.FilterArgument{Kind: &v1.FilterArgument_Uint64{Uint64: k.Uint64.Min.Value}}
					arg2 := &v1.FilterArgument{Kind: &v1.FilterArgument_Uint64{Uint64: k.Uint64.Max.Value}}
					clause.Arguments = append(clause.Arguments, arg1, arg2)
				} else {
					if k.Uint64.Min != nil {
						clause.Predicate = fmt.Sprintf(`%s >= ?`, filter.Field)
						clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_Uint64{Uint64: k.Uint64.Min.Value}})
					}
					if k.Uint64.Max != nil {
						clause.Predicate = fmt.Sprintf(`%s <= ?`, filter.Field)
						clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_Uint64{Uint64: k.Uint64.Max.Value}})
					}
				}
			case *v1.Range_Date:
				if k.Date.Min != nil && k.Date.Max != nil {
					clause.Predicate = fmt.Sprintf(`%s >= ? AND %s <= ?`, filter.Field, filter.Field)
					arg1 := &v1.FilterArgument{Kind: &v1.FilterArgument_String_{String_: k.Date.Min.Value}}
					arg2 := &v1.FilterArgument{Kind: &v1.FilterArgument_String_{String_: k.Date.Max.Value}}
					clause.Arguments = append(clause.Arguments, arg1, arg2)
				} else {
					if k.Date.Min != nil {
						clause.Predicate = fmt.Sprintf(`%s >= ?`, filter.Field)
						clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_String_{String_: k.Date.Min.Value}})
					}
					if k.Date.Max != nil {
						clause.Predicate = fmt.Sprintf(`%s <= ?`, filter.Field)
						clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_String_{String_: k.Date.Max.Value}})
					}
				}
			case *v1.Range_Timestamp:
				if k.Timestamp.Min != nil && k.Timestamp.Max != nil {
					clause.Predicate = fmt.Sprintf(`%s >= ? AND %s <= ?`, filter.Field, filter.Field)
					arg1 := &v1.FilterArgument{Kind: &v1.FilterArgument_String_{String_: k.Timestamp.Min.AsTime().Format(time.RFC3339Nano)}}
					arg2 := &v1.FilterArgument{Kind: &v1.FilterArgument_String_{String_: k.Timestamp.Max.AsTime().Format(time.RFC3339Nano)}}
					clause.Arguments = append(clause.Arguments, arg1, arg2)
				} else {
					if k.Timestamp.Min != nil {
						clause.Predicate = fmt.Sprintf(`%s >= ?`, filter.Field)
						clause.Predicate = fmt.Sprintf(`%s >= ?`, filter.Field)
						clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_String_{String_: k.Timestamp.Min.AsTime().Format(time.RFC3339Nano)}})
					}
					if k.Timestamp.Max != nil {
						clause.Predicate = fmt.Sprintf(`%s <= ?`, filter.Field)
						clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_String_{String_: k.Timestamp.Max.AsTime().Format(time.RFC3339Nano)}})
					}
				}
			}
		} else {
			clause.Predicate = fmt.Sprintf("%s = ?", filter.Field)
			clause.Arguments = append(clause.Arguments, &v1.FilterArgument{Kind: &v1.FilterArgument_String_{String_: filter.GetValue()}})
		}

		resp.Clauses = append(resp.Clauses, clause)
	}

	return resp
}
