// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: listify/services/sample/v1/sample.proto

package sspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SampleService_GetWidget_FullMethodName   = "/listify.services.sample.v1.SampleService/GetWidget"
	SampleService_ListWidgets_FullMethodName = "/listify.services.sample.v1.SampleService/ListWidgets"
)

// SampleServiceClient is the client API for SampleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SampleServiceClient interface {
	GetWidget(ctx context.Context, in *GetWidgetRequest, opts ...grpc.CallOption) (*GetWidgetResponse, error)
	ListWidgets(ctx context.Context, in *ListWidgetsRequest, opts ...grpc.CallOption) (*ListWidgetsResponse, error)
}

type sampleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSampleServiceClient(cc grpc.ClientConnInterface) SampleServiceClient {
	return &sampleServiceClient{cc}
}

func (c *sampleServiceClient) GetWidget(ctx context.Context, in *GetWidgetRequest, opts ...grpc.CallOption) (*GetWidgetResponse, error) {
	out := new(GetWidgetResponse)
	err := c.cc.Invoke(ctx, SampleService_GetWidget_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sampleServiceClient) ListWidgets(ctx context.Context, in *ListWidgetsRequest, opts ...grpc.CallOption) (*ListWidgetsResponse, error) {
	out := new(ListWidgetsResponse)
	err := c.cc.Invoke(ctx, SampleService_ListWidgets_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SampleServiceServer is the server API for SampleService service.
// All implementations must embed UnimplementedSampleServiceServer
// for forward compatibility
type SampleServiceServer interface {
	GetWidget(context.Context, *GetWidgetRequest) (*GetWidgetResponse, error)
	ListWidgets(context.Context, *ListWidgetsRequest) (*ListWidgetsResponse, error)
	mustEmbedUnimplementedSampleServiceServer()
}

// UnimplementedSampleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSampleServiceServer struct {
}

func (UnimplementedSampleServiceServer) GetWidget(context.Context, *GetWidgetRequest) (*GetWidgetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWidget not implemented")
}
func (UnimplementedSampleServiceServer) ListWidgets(context.Context, *ListWidgetsRequest) (*ListWidgetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWidgets not implemented")
}
func (UnimplementedSampleServiceServer) mustEmbedUnimplementedSampleServiceServer() {}

// UnsafeSampleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SampleServiceServer will
// result in compilation errors.
type UnsafeSampleServiceServer interface {
	mustEmbedUnimplementedSampleServiceServer()
}

func RegisterSampleServiceServer(s grpc.ServiceRegistrar, srv SampleServiceServer) {
	s.RegisterService(&SampleService_ServiceDesc, srv)
}

func _SampleService_GetWidget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWidgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SampleServiceServer).GetWidget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SampleService_GetWidget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SampleServiceServer).GetWidget(ctx, req.(*GetWidgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SampleService_ListWidgets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWidgetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SampleServiceServer).ListWidgets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SampleService_ListWidgets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SampleServiceServer).ListWidgets(ctx, req.(*ListWidgetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SampleService_ServiceDesc is the grpc.ServiceDesc for SampleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SampleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "listify.services.sample.v1.SampleService",
	HandlerType: (*SampleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWidget",
			Handler:    _SampleService_GetWidget_Handler,
		},
		{
			MethodName: "ListWidgets",
			Handler:    _SampleService_ListWidgets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "listify/services/sample/v1/sample.proto",
}
