// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: listify/v1/annotations.proto

package listify

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MethodOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enable bool `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
}

func (x *MethodOptions) Reset() {
	*x = MethodOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_annotations_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodOptions) ProtoMessage() {}

func (x *MethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_annotations_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodOptions.ProtoReflect.Descriptor instead.
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return file_listify_v1_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *MethodOptions) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

type OneofRulesOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filterable bool `protobuf:"varint,1,opt,name=filterable,proto3" json:"filterable,omitempty"`
}

func (x *OneofRulesOptions) Reset() {
	*x = OneofRulesOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_annotations_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneofRulesOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofRulesOptions) ProtoMessage() {}

func (x *OneofRulesOptions) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_annotations_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofRulesOptions.ProtoReflect.Descriptor instead.
func (*OneofRulesOptions) Descriptor() ([]byte, []int) {
	return file_listify_v1_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *OneofRulesOptions) GetFilterable() bool {
	if x != nil {
		return x.Filterable
	}
	return false
}

type FieldRulesOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*FieldRulesOptions_Double
	//	*FieldRulesOptions_Fixed32
	//	*FieldRulesOptions_Fixed64
	//	*FieldRulesOptions_Float
	//	*FieldRulesOptions_Int32
	//	*FieldRulesOptions_Int64
	//	*FieldRulesOptions_Sfixed32
	//	*FieldRulesOptions_Sfixed64
	//	*FieldRulesOptions_Sint32
	//	*FieldRulesOptions_Sint64
	//	*FieldRulesOptions_Uint32
	//	*FieldRulesOptions_Uint64
	//	*FieldRulesOptions_Bool
	//	*FieldRulesOptions_String_
	//	*FieldRulesOptions_Enum
	//	*FieldRulesOptions_Timestamp
	Type isFieldRulesOptions_Type `protobuf_oneof:"type"`
}

func (x *FieldRulesOptions) Reset() {
	*x = FieldRulesOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_annotations_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldRulesOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldRulesOptions) ProtoMessage() {}

func (x *FieldRulesOptions) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_annotations_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldRulesOptions.ProtoReflect.Descriptor instead.
func (*FieldRulesOptions) Descriptor() ([]byte, []int) {
	return file_listify_v1_annotations_proto_rawDescGZIP(), []int{2}
}

func (m *FieldRulesOptions) GetType() isFieldRulesOptions_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *FieldRulesOptions) GetDouble() *NumericRules {
	if x, ok := x.GetType().(*FieldRulesOptions_Double); ok {
		return x.Double
	}
	return nil
}

func (x *FieldRulesOptions) GetFixed32() *NumericRules {
	if x, ok := x.GetType().(*FieldRulesOptions_Fixed32); ok {
		return x.Fixed32
	}
	return nil
}

func (x *FieldRulesOptions) GetFixed64() *NumericRules {
	if x, ok := x.GetType().(*FieldRulesOptions_Fixed64); ok {
		return x.Fixed64
	}
	return nil
}

func (x *FieldRulesOptions) GetFloat() *NumericRules {
	if x, ok := x.GetType().(*FieldRulesOptions_Float); ok {
		return x.Float
	}
	return nil
}

func (x *FieldRulesOptions) GetInt32() *NumericRules {
	if x, ok := x.GetType().(*FieldRulesOptions_Int32); ok {
		return x.Int32
	}
	return nil
}

func (x *FieldRulesOptions) GetInt64() *NumericRules {
	if x, ok := x.GetType().(*FieldRulesOptions_Int64); ok {
		return x.Int64
	}
	return nil
}

func (x *FieldRulesOptions) GetSfixed32() *NumericRules {
	if x, ok := x.GetType().(*FieldRulesOptions_Sfixed32); ok {
		return x.Sfixed32
	}
	return nil
}

func (x *FieldRulesOptions) GetSfixed64() *NumericRules {
	if x, ok := x.GetType().(*FieldRulesOptions_Sfixed64); ok {
		return x.Sfixed64
	}
	return nil
}

func (x *FieldRulesOptions) GetSint32() *NumericRules {
	if x, ok := x.GetType().(*FieldRulesOptions_Sint32); ok {
		return x.Sint32
	}
	return nil
}

func (x *FieldRulesOptions) GetSint64() *NumericRules {
	if x, ok := x.GetType().(*FieldRulesOptions_Sint64); ok {
		return x.Sint64
	}
	return nil
}

func (x *FieldRulesOptions) GetUint32() *NumericRules {
	if x, ok := x.GetType().(*FieldRulesOptions_Uint32); ok {
		return x.Uint32
	}
	return nil
}

func (x *FieldRulesOptions) GetUint64() *NumericRules {
	if x, ok := x.GetType().(*FieldRulesOptions_Uint64); ok {
		return x.Uint64
	}
	return nil
}

func (x *FieldRulesOptions) GetBool() *BoolRules {
	if x, ok := x.GetType().(*FieldRulesOptions_Bool); ok {
		return x.Bool
	}
	return nil
}

func (x *FieldRulesOptions) GetString_() *StringRules {
	if x, ok := x.GetType().(*FieldRulesOptions_String_); ok {
		return x.String_
	}
	return nil
}

func (x *FieldRulesOptions) GetEnum() *EnumRules {
	if x, ok := x.GetType().(*FieldRulesOptions_Enum); ok {
		return x.Enum
	}
	return nil
}

func (x *FieldRulesOptions) GetTimestamp() *TimestampRules {
	if x, ok := x.GetType().(*FieldRulesOptions_Timestamp); ok {
		return x.Timestamp
	}
	return nil
}

type isFieldRulesOptions_Type interface {
	isFieldRulesOptions_Type()
}

type FieldRulesOptions_Double struct {
	Double *NumericRules `protobuf:"bytes,1,opt,name=double,proto3,oneof"`
}

type FieldRulesOptions_Fixed32 struct {
	Fixed32 *NumericRules `protobuf:"bytes,2,opt,name=fixed32,proto3,oneof"`
}

type FieldRulesOptions_Fixed64 struct {
	Fixed64 *NumericRules `protobuf:"bytes,3,opt,name=fixed64,proto3,oneof"`
}

type FieldRulesOptions_Float struct {
	Float *NumericRules `protobuf:"bytes,4,opt,name=float,proto3,oneof"`
}

type FieldRulesOptions_Int32 struct {
	Int32 *NumericRules `protobuf:"bytes,5,opt,name=int32,proto3,oneof"`
}

type FieldRulesOptions_Int64 struct {
	Int64 *NumericRules `protobuf:"bytes,6,opt,name=int64,proto3,oneof"`
}

type FieldRulesOptions_Sfixed32 struct {
	Sfixed32 *NumericRules `protobuf:"bytes,7,opt,name=sfixed32,proto3,oneof"`
}

type FieldRulesOptions_Sfixed64 struct {
	Sfixed64 *NumericRules `protobuf:"bytes,8,opt,name=sfixed64,proto3,oneof"`
}

type FieldRulesOptions_Sint32 struct {
	Sint32 *NumericRules `protobuf:"bytes,9,opt,name=sint32,proto3,oneof"`
}

type FieldRulesOptions_Sint64 struct {
	Sint64 *NumericRules `protobuf:"bytes,10,opt,name=sint64,proto3,oneof"`
}

type FieldRulesOptions_Uint32 struct {
	Uint32 *NumericRules `protobuf:"bytes,11,opt,name=uint32,proto3,oneof"`
}

type FieldRulesOptions_Uint64 struct {
	Uint64 *NumericRules `protobuf:"bytes,12,opt,name=uint64,proto3,oneof"`
}

type FieldRulesOptions_Bool struct {
	Bool *BoolRules `protobuf:"bytes,13,opt,name=bool,proto3,oneof"`
}

type FieldRulesOptions_String_ struct {
	String_ *StringRules `protobuf:"bytes,14,opt,name=string,proto3,oneof"`
}

type FieldRulesOptions_Enum struct {
	Enum *EnumRules `protobuf:"bytes,20,opt,name=enum,proto3,oneof"`
}

type FieldRulesOptions_Timestamp struct {
	Timestamp *TimestampRules `protobuf:"bytes,30,opt,name=timestamp,proto3,oneof"`
}

func (*FieldRulesOptions_Double) isFieldRulesOptions_Type() {}

func (*FieldRulesOptions_Fixed32) isFieldRulesOptions_Type() {}

func (*FieldRulesOptions_Fixed64) isFieldRulesOptions_Type() {}

func (*FieldRulesOptions_Float) isFieldRulesOptions_Type() {}

func (*FieldRulesOptions_Int32) isFieldRulesOptions_Type() {}

func (*FieldRulesOptions_Int64) isFieldRulesOptions_Type() {}

func (*FieldRulesOptions_Sfixed32) isFieldRulesOptions_Type() {}

func (*FieldRulesOptions_Sfixed64) isFieldRulesOptions_Type() {}

func (*FieldRulesOptions_Sint32) isFieldRulesOptions_Type() {}

func (*FieldRulesOptions_Sint64) isFieldRulesOptions_Type() {}

func (*FieldRulesOptions_Uint32) isFieldRulesOptions_Type() {}

func (*FieldRulesOptions_Uint64) isFieldRulesOptions_Type() {}

func (*FieldRulesOptions_Bool) isFieldRulesOptions_Type() {}

func (*FieldRulesOptions_String_) isFieldRulesOptions_Type() {}

func (*FieldRulesOptions_Enum) isFieldRulesOptions_Type() {}

func (*FieldRulesOptions_Timestamp) isFieldRulesOptions_Type() {}

type NumericRules struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filterable bool `protobuf:"varint,1,opt,name=filterable,proto3" json:"filterable,omitempty"`
	Sortable   bool `protobuf:"varint,2,opt,name=sortable,proto3" json:"sortable,omitempty"`
}

func (x *NumericRules) Reset() {
	*x = NumericRules{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_annotations_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumericRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumericRules) ProtoMessage() {}

func (x *NumericRules) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_annotations_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumericRules.ProtoReflect.Descriptor instead.
func (*NumericRules) Descriptor() ([]byte, []int) {
	return file_listify_v1_annotations_proto_rawDescGZIP(), []int{3}
}

func (x *NumericRules) GetFilterable() bool {
	if x != nil {
		return x.Filterable
	}
	return false
}

func (x *NumericRules) GetSortable() bool {
	if x != nil {
		return x.Sortable
	}
	return false
}

type BoolRules struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filterable bool `protobuf:"varint,1,opt,name=filterable,proto3" json:"filterable,omitempty"`
}

func (x *BoolRules) Reset() {
	*x = BoolRules{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_annotations_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoolRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolRules) ProtoMessage() {}

func (x *BoolRules) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_annotations_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolRules.ProtoReflect.Descriptor instead.
func (*BoolRules) Descriptor() ([]byte, []int) {
	return file_listify_v1_annotations_proto_rawDescGZIP(), []int{4}
}

func (x *BoolRules) GetFilterable() bool {
	if x != nil {
		return x.Filterable
	}
	return false
}

type StringRules struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to WellKnown:
	//
	//	*StringRules_OpenText
	//	*StringRules_Date
	//	*StringRules_ForeignKey
	WellKnown isStringRules_WellKnown `protobuf_oneof:"well_known"`
}

func (x *StringRules) Reset() {
	*x = StringRules{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_annotations_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringRules) ProtoMessage() {}

func (x *StringRules) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_annotations_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringRules.ProtoReflect.Descriptor instead.
func (*StringRules) Descriptor() ([]byte, []int) {
	return file_listify_v1_annotations_proto_rawDescGZIP(), []int{5}
}

func (m *StringRules) GetWellKnown() isStringRules_WellKnown {
	if m != nil {
		return m.WellKnown
	}
	return nil
}

func (x *StringRules) GetOpenText() *OpenTextRules {
	if x, ok := x.GetWellKnown().(*StringRules_OpenText); ok {
		return x.OpenText
	}
	return nil
}

func (x *StringRules) GetDate() *DateRules {
	if x, ok := x.GetWellKnown().(*StringRules_Date); ok {
		return x.Date
	}
	return nil
}

func (x *StringRules) GetForeignKey() *ForeignKeyRules {
	if x, ok := x.GetWellKnown().(*StringRules_ForeignKey); ok {
		return x.ForeignKey
	}
	return nil
}

type isStringRules_WellKnown interface {
	isStringRules_WellKnown()
}

type StringRules_OpenText struct {
	OpenText *OpenTextRules `protobuf:"bytes,1,opt,name=open_text,json=openText,proto3,oneof"`
}

type StringRules_Date struct {
	Date *DateRules `protobuf:"bytes,2,opt,name=date,proto3,oneof"`
}

type StringRules_ForeignKey struct {
	ForeignKey *ForeignKeyRules `protobuf:"bytes,3,opt,name=foreign_key,json=foreignKey,proto3,oneof"`
}

func (*StringRules_OpenText) isStringRules_WellKnown() {}

func (*StringRules_Date) isStringRules_WellKnown() {}

func (*StringRules_ForeignKey) isStringRules_WellKnown() {}

type OpenTextRules struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Searchable bool `protobuf:"varint,1,opt,name=searchable,proto3" json:"searchable,omitempty"`
}

func (x *OpenTextRules) Reset() {
	*x = OpenTextRules{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_annotations_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenTextRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTextRules) ProtoMessage() {}

func (x *OpenTextRules) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_annotations_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTextRules.ProtoReflect.Descriptor instead.
func (*OpenTextRules) Descriptor() ([]byte, []int) {
	return file_listify_v1_annotations_proto_rawDescGZIP(), []int{6}
}

func (x *OpenTextRules) GetSearchable() bool {
	if x != nil {
		return x.Searchable
	}
	return false
}

type DateRules struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filterable bool `protobuf:"varint,1,opt,name=filterable,proto3" json:"filterable,omitempty"`
}

func (x *DateRules) Reset() {
	*x = DateRules{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_annotations_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DateRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateRules) ProtoMessage() {}

func (x *DateRules) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_annotations_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateRules.ProtoReflect.Descriptor instead.
func (*DateRules) Descriptor() ([]byte, []int) {
	return file_listify_v1_annotations_proto_rawDescGZIP(), []int{7}
}

func (x *DateRules) GetFilterable() bool {
	if x != nil {
		return x.Filterable
	}
	return false
}

type ForeignKeyRules struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*ForeignKeyRules_UniqueString
	//	*ForeignKeyRules_Uuid
	Type isForeignKeyRules_Type `protobuf_oneof:"type"`
}

func (x *ForeignKeyRules) Reset() {
	*x = ForeignKeyRules{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_annotations_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForeignKeyRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForeignKeyRules) ProtoMessage() {}

func (x *ForeignKeyRules) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_annotations_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForeignKeyRules.ProtoReflect.Descriptor instead.
func (*ForeignKeyRules) Descriptor() ([]byte, []int) {
	return file_listify_v1_annotations_proto_rawDescGZIP(), []int{8}
}

func (m *ForeignKeyRules) GetType() isForeignKeyRules_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *ForeignKeyRules) GetUniqueString() *UniqueStringRules {
	if x, ok := x.GetType().(*ForeignKeyRules_UniqueString); ok {
		return x.UniqueString
	}
	return nil
}

func (x *ForeignKeyRules) GetUuid() *UuidRules {
	if x, ok := x.GetType().(*ForeignKeyRules_Uuid); ok {
		return x.Uuid
	}
	return nil
}

type isForeignKeyRules_Type interface {
	isForeignKeyRules_Type()
}

type ForeignKeyRules_UniqueString struct {
	UniqueString *UniqueStringRules `protobuf:"bytes,1,opt,name=unique_string,json=uniqueString,proto3,oneof"`
}

type ForeignKeyRules_Uuid struct {
	Uuid *UuidRules `protobuf:"bytes,2,opt,name=uuid,proto3,oneof"`
}

func (*ForeignKeyRules_UniqueString) isForeignKeyRules_Type() {}

func (*ForeignKeyRules_Uuid) isForeignKeyRules_Type() {}

type UniqueStringRules struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filterable bool `protobuf:"varint,1,opt,name=filterable,proto3" json:"filterable,omitempty"`
}

func (x *UniqueStringRules) Reset() {
	*x = UniqueStringRules{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_annotations_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniqueStringRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniqueStringRules) ProtoMessage() {}

func (x *UniqueStringRules) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_annotations_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniqueStringRules.ProtoReflect.Descriptor instead.
func (*UniqueStringRules) Descriptor() ([]byte, []int) {
	return file_listify_v1_annotations_proto_rawDescGZIP(), []int{9}
}

func (x *UniqueStringRules) GetFilterable() bool {
	if x != nil {
		return x.Filterable
	}
	return false
}

type UuidRules struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filterable bool `protobuf:"varint,1,opt,name=filterable,proto3" json:"filterable,omitempty"`
}

func (x *UuidRules) Reset() {
	*x = UuidRules{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_annotations_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UuidRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UuidRules) ProtoMessage() {}

func (x *UuidRules) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_annotations_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UuidRules.ProtoReflect.Descriptor instead.
func (*UuidRules) Descriptor() ([]byte, []int) {
	return file_listify_v1_annotations_proto_rawDescGZIP(), []int{10}
}

func (x *UuidRules) GetFilterable() bool {
	if x != nil {
		return x.Filterable
	}
	return false
}

type EnumRules struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filterable bool `protobuf:"varint,1,opt,name=filterable,proto3" json:"filterable,omitempty"`
}

func (x *EnumRules) Reset() {
	*x = EnumRules{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_annotations_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnumRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumRules) ProtoMessage() {}

func (x *EnumRules) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_annotations_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumRules.ProtoReflect.Descriptor instead.
func (*EnumRules) Descriptor() ([]byte, []int) {
	return file_listify_v1_annotations_proto_rawDescGZIP(), []int{11}
}

func (x *EnumRules) GetFilterable() bool {
	if x != nil {
		return x.Filterable
	}
	return false
}

type TimestampRules struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filterable bool `protobuf:"varint,1,opt,name=filterable,proto3" json:"filterable,omitempty"`
	Sortable   bool `protobuf:"varint,2,opt,name=sortable,proto3" json:"sortable,omitempty"`
}

func (x *TimestampRules) Reset() {
	*x = TimestampRules{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_annotations_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimestampRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampRules) ProtoMessage() {}

func (x *TimestampRules) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_annotations_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampRules.ProtoReflect.Descriptor instead.
func (*TimestampRules) Descriptor() ([]byte, []int) {
	return file_listify_v1_annotations_proto_rawDescGZIP(), []int{12}
}

func (x *TimestampRules) GetFilterable() bool {
	if x != nil {
		return x.Filterable
	}
	return false
}

func (x *TimestampRules) GetSortable() bool {
	if x != nil {
		return x.Sortable
	}
	return false
}

var file_listify_v1_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MethodOptions)(nil),
		Field:         86510000,
		Name:          "listify.v1.api",
		Tag:           "bytes,86510000,opt,name=api",
		Filename:      "listify/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldRulesOptions)(nil),
		Field:         86510001,
		Name:          "listify.v1.rules",
		Tag:           "bytes,86510001,opt,name=rules",
		Filename:      "listify/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.OneofOptions)(nil),
		ExtensionType: (*OneofRulesOptions)(nil),
		Field:         86510002,
		Name:          "listify.v1.oneof_rules",
		Tag:           "bytes,86510002,opt,name=oneof_rules",
		Filename:      "listify/v1/annotations.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional listify.v1.MethodOptions api = 86510000;
	E_Api = &file_listify_v1_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional listify.v1.FieldRulesOptions rules = 86510001;
	E_Rules = &file_listify_v1_annotations_proto_extTypes[1]
)

// Extension fields to descriptorpb.OneofOptions.
var (
	// optional listify.v1.OneofRulesOptions oneof_rules = 86510002;
	E_OneofRules = &file_listify_v1_annotations_proto_extTypes[2]
)

var File_listify_v1_annotations_proto protoreflect.FileDescriptor

var file_listify_v1_annotations_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x0d,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x33, 0x0a, 0x11, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x52, 0x75,
	0x6c, 0x65, 0x73, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x22, 0xda, 0x06, 0x0a, 0x11, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x32, 0x0a, 0x06, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x75,
	0x6d, 0x65, 0x72, 0x69, 0x63, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x48, 0x00, 0x52, 0x06, 0x64, 0x6f,
	0x75, 0x62, 0x6c, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x66, 0x69, 0x78, 0x65, 0x64, 0x33, 0x32, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2e,
	0x76, 0x31, 0x2e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x48,
	0x00, 0x52, 0x07, 0x66, 0x69, 0x78, 0x65, 0x64, 0x33, 0x32, 0x12, 0x34, 0x0a, 0x07, 0x66, 0x69,
	0x78, 0x65, 0x64, 0x36, 0x34, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x69,
	0x73, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63,
	0x52, 0x75, 0x6c, 0x65, 0x73, 0x48, 0x00, 0x52, 0x07, 0x66, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34,
	0x12, 0x30, 0x0a, 0x05, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x75, 0x6d,
	0x65, 0x72, 0x69, 0x63, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x48, 0x00, 0x52, 0x05, 0x66, 0x6c, 0x6f,
	0x61, 0x74, 0x12, 0x30, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4e,
	0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x48, 0x00, 0x52, 0x05, 0x69,
	0x6e, 0x74, 0x33, 0x32, 0x12, 0x30, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x48, 0x00, 0x52,
	0x05, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x36, 0x0a, 0x08, 0x73, 0x66, 0x69, 0x78, 0x65, 0x64,
	0x33, 0x32, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69,
	0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x52, 0x75, 0x6c,
	0x65, 0x73, 0x48, 0x00, 0x52, 0x08, 0x73, 0x66, 0x69, 0x78, 0x65, 0x64, 0x33, 0x32, 0x12, 0x36,
	0x0a, 0x08, 0x73, 0x66, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x75,
	0x6d, 0x65, 0x72, 0x69, 0x63, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x48, 0x00, 0x52, 0x08, 0x73, 0x66,
	0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x12, 0x32, 0x0a, 0x06, 0x73, 0x69, 0x6e, 0x74, 0x33, 0x32,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x52, 0x75, 0x6c, 0x65, 0x73,
	0x48, 0x00, 0x52, 0x06, 0x73, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x32, 0x0a, 0x06, 0x73, 0x69,
	0x6e, 0x74, 0x36, 0x34, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x69, 0x73,
	0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x52,
	0x75, 0x6c, 0x65, 0x73, 0x48, 0x00, 0x52, 0x06, 0x73, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x32,
	0x0a, 0x06, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x75, 0x6d, 0x65,
	0x72, 0x69, 0x63, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x48, 0x00, 0x52, 0x06, 0x75, 0x69, 0x6e, 0x74,
	0x33, 0x32, 0x12, 0x32, 0x0a, 0x06, 0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e,
	0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x48, 0x00, 0x52, 0x06,
	0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x2b, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x0d,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76,
	0x31, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x48, 0x00, 0x52, 0x04, 0x62,
	0x6f, 0x6f, 0x6c, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x0e, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x48, 0x00, 0x52, 0x06,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x2b, 0x0a, 0x04, 0x65, 0x6e, 0x75, 0x6d, 0x18, 0x14,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76,
	0x31, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x48, 0x00, 0x52, 0x04, 0x65,
	0x6e, 0x75, 0x6d, 0x12, 0x3a, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x1e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x75, 0x6c,
	0x65, 0x73, 0x48, 0x00, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x42,
	0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x4a, 0x0a, 0x0c, 0x4e, 0x75, 0x6d, 0x65, 0x72,
	0x69, 0x63, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6f, 0x72, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x73, 0x6f, 0x72, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x22, 0x2b, 0x0a, 0x09, 0x42, 0x6f, 0x6f, 0x6c, 0x52, 0x75, 0x6c, 0x65, 0x73,
	0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65,
	0x22, 0xc2, 0x01, 0x0a, 0x0b, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x75, 0x6c, 0x65, 0x73,
	0x12, 0x38, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x65, 0x78, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x48, 0x00,
	0x52, 0x08, 0x6f, 0x70, 0x65, 0x6e, 0x54, 0x65, 0x78, 0x74, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69,
	0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x48,
	0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x3e, 0x0a, 0x0b, 0x66, 0x6f, 0x72, 0x65, 0x69,
	0x67, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6c,
	0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6f, 0x72, 0x65, 0x69, 0x67,
	0x6e, 0x4b, 0x65, 0x79, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x48, 0x00, 0x52, 0x0a, 0x66, 0x6f, 0x72,
	0x65, 0x69, 0x67, 0x6e, 0x4b, 0x65, 0x79, 0x42, 0x0c, 0x0a, 0x0a, 0x77, 0x65, 0x6c, 0x6c, 0x5f,
	0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x22, 0x2f, 0x0a, 0x0d, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x65, 0x78,
	0x74, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x2b, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x65, 0x52, 0x75,
	0x6c, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x61, 0x62, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x61,
	0x62, 0x6c, 0x65, 0x22, 0x8c, 0x01, 0x0a, 0x0f, 0x46, 0x6f, 0x72, 0x65, 0x69, 0x67, 0x6e, 0x4b,
	0x65, 0x79, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x44, 0x0a, 0x0d, 0x75, 0x6e, 0x69, 0x71, 0x75,
	0x65, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e, 0x69, 0x71,
	0x75, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x48, 0x00, 0x52,
	0x0c, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x2b, 0x0a,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6c, 0x69,
	0x73, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x75, 0x69, 0x64, 0x52, 0x75, 0x6c,
	0x65, 0x73, 0x48, 0x00, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x22, 0x33, 0x0a, 0x11, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x2b, 0x0a, 0x09, 0x55, 0x75, 0x69, 0x64, 0x52,
	0x75, 0x6c, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x61, 0x62,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x61, 0x62, 0x6c, 0x65, 0x22, 0x2b, 0x0a, 0x09, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x75, 0x6c, 0x65,
	0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x61, 0x62, 0x6c,
	0x65, 0x22, 0x4c, 0x0a, 0x0e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x75,
	0x6c, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x61, 0x62, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x61,
	0x62, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6f, 0x72, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x73, 0x6f, 0x72, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x3a,
	0x4e, 0x0a, 0x03, 0x61, 0x70, 0x69, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xb0, 0x93, 0xa0, 0x29, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x03, 0x61, 0x70, 0x69, 0x3a,
	0x55, 0x0a, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xb1, 0x93, 0xa0, 0x29, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x3a, 0x60, 0x0a, 0x0b, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x5f,
	0x72, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0xb2, 0x93, 0xa0, 0x29, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x6e, 0x65, 0x6f, 0x66,
	0x52, 0x75, 0x6c, 0x65, 0x73, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0a, 0x6f, 0x6e,
	0x65, 0x6f, 0x66, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x65, 0x6e, 0x74, 0x6f, 0x70, 0x73, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66,
	0x79, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2f, 0x76, 0x31, 0x3b, 0x6c, 0x69, 0x73,
	0x74, 0x69, 0x66, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_listify_v1_annotations_proto_rawDescOnce sync.Once
	file_listify_v1_annotations_proto_rawDescData = file_listify_v1_annotations_proto_rawDesc
)

func file_listify_v1_annotations_proto_rawDescGZIP() []byte {
	file_listify_v1_annotations_proto_rawDescOnce.Do(func() {
		file_listify_v1_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(file_listify_v1_annotations_proto_rawDescData)
	})
	return file_listify_v1_annotations_proto_rawDescData
}

var file_listify_v1_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_listify_v1_annotations_proto_goTypes = []interface{}{
	(*MethodOptions)(nil),              // 0: listify.v1.MethodOptions
	(*OneofRulesOptions)(nil),          // 1: listify.v1.OneofRulesOptions
	(*FieldRulesOptions)(nil),          // 2: listify.v1.FieldRulesOptions
	(*NumericRules)(nil),               // 3: listify.v1.NumericRules
	(*BoolRules)(nil),                  // 4: listify.v1.BoolRules
	(*StringRules)(nil),                // 5: listify.v1.StringRules
	(*OpenTextRules)(nil),              // 6: listify.v1.OpenTextRules
	(*DateRules)(nil),                  // 7: listify.v1.DateRules
	(*ForeignKeyRules)(nil),            // 8: listify.v1.ForeignKeyRules
	(*UniqueStringRules)(nil),          // 9: listify.v1.UniqueStringRules
	(*UuidRules)(nil),                  // 10: listify.v1.UuidRules
	(*EnumRules)(nil),                  // 11: listify.v1.EnumRules
	(*TimestampRules)(nil),             // 12: listify.v1.TimestampRules
	(*descriptorpb.MethodOptions)(nil), // 13: google.protobuf.MethodOptions
	(*descriptorpb.FieldOptions)(nil),  // 14: google.protobuf.FieldOptions
	(*descriptorpb.OneofOptions)(nil),  // 15: google.protobuf.OneofOptions
}
var file_listify_v1_annotations_proto_depIdxs = []int32{
	3,  // 0: listify.v1.FieldRulesOptions.double:type_name -> listify.v1.NumericRules
	3,  // 1: listify.v1.FieldRulesOptions.fixed32:type_name -> listify.v1.NumericRules
	3,  // 2: listify.v1.FieldRulesOptions.fixed64:type_name -> listify.v1.NumericRules
	3,  // 3: listify.v1.FieldRulesOptions.float:type_name -> listify.v1.NumericRules
	3,  // 4: listify.v1.FieldRulesOptions.int32:type_name -> listify.v1.NumericRules
	3,  // 5: listify.v1.FieldRulesOptions.int64:type_name -> listify.v1.NumericRules
	3,  // 6: listify.v1.FieldRulesOptions.sfixed32:type_name -> listify.v1.NumericRules
	3,  // 7: listify.v1.FieldRulesOptions.sfixed64:type_name -> listify.v1.NumericRules
	3,  // 8: listify.v1.FieldRulesOptions.sint32:type_name -> listify.v1.NumericRules
	3,  // 9: listify.v1.FieldRulesOptions.sint64:type_name -> listify.v1.NumericRules
	3,  // 10: listify.v1.FieldRulesOptions.uint32:type_name -> listify.v1.NumericRules
	3,  // 11: listify.v1.FieldRulesOptions.uint64:type_name -> listify.v1.NumericRules
	4,  // 12: listify.v1.FieldRulesOptions.bool:type_name -> listify.v1.BoolRules
	5,  // 13: listify.v1.FieldRulesOptions.string:type_name -> listify.v1.StringRules
	11, // 14: listify.v1.FieldRulesOptions.enum:type_name -> listify.v1.EnumRules
	12, // 15: listify.v1.FieldRulesOptions.timestamp:type_name -> listify.v1.TimestampRules
	6,  // 16: listify.v1.StringRules.open_text:type_name -> listify.v1.OpenTextRules
	7,  // 17: listify.v1.StringRules.date:type_name -> listify.v1.DateRules
	8,  // 18: listify.v1.StringRules.foreign_key:type_name -> listify.v1.ForeignKeyRules
	9,  // 19: listify.v1.ForeignKeyRules.unique_string:type_name -> listify.v1.UniqueStringRules
	10, // 20: listify.v1.ForeignKeyRules.uuid:type_name -> listify.v1.UuidRules
	13, // 21: listify.v1.api:extendee -> google.protobuf.MethodOptions
	14, // 22: listify.v1.rules:extendee -> google.protobuf.FieldOptions
	15, // 23: listify.v1.oneof_rules:extendee -> google.protobuf.OneofOptions
	0,  // 24: listify.v1.api:type_name -> listify.v1.MethodOptions
	2,  // 25: listify.v1.rules:type_name -> listify.v1.FieldRulesOptions
	1,  // 26: listify.v1.oneof_rules:type_name -> listify.v1.OneofRulesOptions
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	24, // [24:27] is the sub-list for extension type_name
	21, // [21:24] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_listify_v1_annotations_proto_init() }
func file_listify_v1_annotations_proto_init() {
	if File_listify_v1_annotations_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_listify_v1_annotations_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MethodOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_annotations_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneofRulesOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_annotations_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldRulesOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_annotations_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumericRules); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_annotations_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoolRules); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_annotations_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringRules); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_annotations_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenTextRules); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_annotations_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DateRules); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_annotations_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForeignKeyRules); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_annotations_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniqueStringRules); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_annotations_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UuidRules); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_annotations_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnumRules); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_annotations_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimestampRules); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_listify_v1_annotations_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*FieldRulesOptions_Double)(nil),
		(*FieldRulesOptions_Fixed32)(nil),
		(*FieldRulesOptions_Fixed64)(nil),
		(*FieldRulesOptions_Float)(nil),
		(*FieldRulesOptions_Int32)(nil),
		(*FieldRulesOptions_Int64)(nil),
		(*FieldRulesOptions_Sfixed32)(nil),
		(*FieldRulesOptions_Sfixed64)(nil),
		(*FieldRulesOptions_Sint32)(nil),
		(*FieldRulesOptions_Sint64)(nil),
		(*FieldRulesOptions_Uint32)(nil),
		(*FieldRulesOptions_Uint64)(nil),
		(*FieldRulesOptions_Bool)(nil),
		(*FieldRulesOptions_String_)(nil),
		(*FieldRulesOptions_Enum)(nil),
		(*FieldRulesOptions_Timestamp)(nil),
	}
	file_listify_v1_annotations_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*StringRules_OpenText)(nil),
		(*StringRules_Date)(nil),
		(*StringRules_ForeignKey)(nil),
	}
	file_listify_v1_annotations_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*ForeignKeyRules_UniqueString)(nil),
		(*ForeignKeyRules_Uuid)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_listify_v1_annotations_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_listify_v1_annotations_proto_goTypes,
		DependencyIndexes: file_listify_v1_annotations_proto_depIdxs,
		MessageInfos:      file_listify_v1_annotations_proto_msgTypes,
		ExtensionInfos:    file_listify_v1_annotations_proto_extTypes,
	}.Build()
	File_listify_v1_annotations_proto = out.File
	file_listify_v1_annotations_proto_rawDesc = nil
	file_listify_v1_annotations_proto_goTypes = nil
	file_listify_v1_annotations_proto_depIdxs = nil
}
