// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: listify/v1/fields.proto

package listify

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Page struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NextPage     string `protobuf:"bytes,1,opt,name=next_page,json=nextPage,proto3" json:"next_page,omitempty"`
	FinalPage    bool   `protobuf:"varint,2,opt,name=final_page,json=finalPage,proto3" json:"final_page,omitempty"`
	TotalRecords int64  `protobuf:"varint,3,opt,name=total_records,json=totalRecords,proto3" json:"total_records,omitempty"`
}

func (x *Page) Reset() {
	*x = Page{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_fields_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_fields_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_listify_v1_fields_proto_rawDescGZIP(), []int{0}
}

func (x *Page) GetNextPage() string {
	if x != nil {
		return x.NextPage
	}
	return ""
}

func (x *Page) GetFinalPage() bool {
	if x != nil {
		return x.FinalPage
	}
	return false
}

func (x *Page) GetTotalRecords() int64 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

type Search struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *Search) Reset() {
	*x = Search{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_fields_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Search) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search) ProtoMessage() {}

func (x *Search) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_fields_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search.ProtoReflect.Descriptor instead.
func (*Search) Descriptor() ([]byte, []int) {
	return file_listify_v1_fields_proto_rawDescGZIP(), []int{1}
}

func (x *Search) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type Sort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field      string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Descending bool   `protobuf:"varint,2,opt,name=descending,proto3" json:"descending,omitempty"`
}

func (x *Sort) Reset() {
	*x = Sort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_fields_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sort) ProtoMessage() {}

func (x *Sort) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_fields_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sort.ProtoReflect.Descriptor instead.
func (*Sort) Descriptor() ([]byte, []int) {
	return file_listify_v1_fields_proto_rawDescGZIP(), []int{2}
}

func (x *Sort) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Sort) GetDescending() bool {
	if x != nil {
		return x.Descending
	}
	return false
}

type Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// Types that are assignable to FilterValue:
	//
	//	*Filter_Value
	//	*Filter_Range
	FilterValue isFilter_FilterValue `protobuf_oneof:"filter_value"`
}

func (x *Filter) Reset() {
	*x = Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_fields_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_fields_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_listify_v1_fields_proto_rawDescGZIP(), []int{3}
}

func (x *Filter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (m *Filter) GetFilterValue() isFilter_FilterValue {
	if m != nil {
		return m.FilterValue
	}
	return nil
}

func (x *Filter) GetValue() string {
	if x, ok := x.GetFilterValue().(*Filter_Value); ok {
		return x.Value
	}
	return ""
}

func (x *Filter) GetRange() *Range {
	if x, ok := x.GetFilterValue().(*Filter_Range); ok {
		return x.Range
	}
	return nil
}

type isFilter_FilterValue interface {
	isFilter_FilterValue()
}

type Filter_Value struct {
	Value string `protobuf:"bytes,2,opt,name=value,proto3,oneof"`
}

type Filter_Range struct {
	Range *Range `protobuf:"bytes,3,opt,name=range,proto3,oneof"`
}

func (*Filter_Value) isFilter_FilterValue() {}

func (*Filter_Range) isFilter_FilterValue() {}

type Range struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*Range_Double
	//	*Range_Fixed32
	//	*Range_Fixed64
	//	*Range_Float
	//	*Range_Int32
	//	*Range_Int64
	//	*Range_Sfixed32
	//	*Range_Sfixed64
	//	*Range_Sint32
	//	*Range_Sint64
	//	*Range_Uint32
	//	*Range_Uint64
	//	*Range_Timestamp
	//	*Range_Date
	Type isRange_Type `protobuf_oneof:"type"`
}

func (x *Range) Reset() {
	*x = Range{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_fields_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range) ProtoMessage() {}

func (x *Range) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_fields_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range.ProtoReflect.Descriptor instead.
func (*Range) Descriptor() ([]byte, []int) {
	return file_listify_v1_fields_proto_rawDescGZIP(), []int{4}
}

func (m *Range) GetType() isRange_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Range) GetDouble() *DoubleRange {
	if x, ok := x.GetType().(*Range_Double); ok {
		return x.Double
	}
	return nil
}

func (x *Range) GetFixed32() *Fixed32Range {
	if x, ok := x.GetType().(*Range_Fixed32); ok {
		return x.Fixed32
	}
	return nil
}

func (x *Range) GetFixed64() *Fixed64Range {
	if x, ok := x.GetType().(*Range_Fixed64); ok {
		return x.Fixed64
	}
	return nil
}

func (x *Range) GetFloat() *FloatRange {
	if x, ok := x.GetType().(*Range_Float); ok {
		return x.Float
	}
	return nil
}

func (x *Range) GetInt32() *Int32Range {
	if x, ok := x.GetType().(*Range_Int32); ok {
		return x.Int32
	}
	return nil
}

func (x *Range) GetInt64() *Int64Range {
	if x, ok := x.GetType().(*Range_Int64); ok {
		return x.Int64
	}
	return nil
}

func (x *Range) GetSfixed32() *SFixed32Range {
	if x, ok := x.GetType().(*Range_Sfixed32); ok {
		return x.Sfixed32
	}
	return nil
}

func (x *Range) GetSfixed64() *SFixed64Range {
	if x, ok := x.GetType().(*Range_Sfixed64); ok {
		return x.Sfixed64
	}
	return nil
}

func (x *Range) GetSint32() *SInt32Range {
	if x, ok := x.GetType().(*Range_Sint32); ok {
		return x.Sint32
	}
	return nil
}

func (x *Range) GetSint64() *SInt64Range {
	if x, ok := x.GetType().(*Range_Sint64); ok {
		return x.Sint64
	}
	return nil
}

func (x *Range) GetUint32() *UInt32Range {
	if x, ok := x.GetType().(*Range_Uint32); ok {
		return x.Uint32
	}
	return nil
}

func (x *Range) GetUint64() *UInt64Range {
	if x, ok := x.GetType().(*Range_Uint64); ok {
		return x.Uint64
	}
	return nil
}

func (x *Range) GetTimestamp() *TimestampRange {
	if x, ok := x.GetType().(*Range_Timestamp); ok {
		return x.Timestamp
	}
	return nil
}

func (x *Range) GetDate() *DateRange {
	if x, ok := x.GetType().(*Range_Date); ok {
		return x.Date
	}
	return nil
}

type isRange_Type interface {
	isRange_Type()
}

type Range_Double struct {
	Double *DoubleRange `protobuf:"bytes,1,opt,name=double,proto3,oneof"`
}

type Range_Fixed32 struct {
	Fixed32 *Fixed32Range `protobuf:"bytes,2,opt,name=fixed32,proto3,oneof"`
}

type Range_Fixed64 struct {
	Fixed64 *Fixed64Range `protobuf:"bytes,3,opt,name=fixed64,proto3,oneof"`
}

type Range_Float struct {
	Float *FloatRange `protobuf:"bytes,4,opt,name=float,proto3,oneof"`
}

type Range_Int32 struct {
	Int32 *Int32Range `protobuf:"bytes,5,opt,name=int32,proto3,oneof"`
}

type Range_Int64 struct {
	Int64 *Int64Range `protobuf:"bytes,6,opt,name=int64,proto3,oneof"`
}

type Range_Sfixed32 struct {
	Sfixed32 *SFixed32Range `protobuf:"bytes,7,opt,name=sfixed32,proto3,oneof"`
}

type Range_Sfixed64 struct {
	Sfixed64 *SFixed64Range `protobuf:"bytes,8,opt,name=sfixed64,proto3,oneof"`
}

type Range_Sint32 struct {
	Sint32 *SInt32Range `protobuf:"bytes,9,opt,name=sint32,proto3,oneof"`
}

type Range_Sint64 struct {
	Sint64 *SInt64Range `protobuf:"bytes,10,opt,name=sint64,proto3,oneof"`
}

type Range_Uint32 struct {
	Uint32 *UInt32Range `protobuf:"bytes,11,opt,name=uint32,proto3,oneof"`
}

type Range_Uint64 struct {
	Uint64 *UInt64Range `protobuf:"bytes,12,opt,name=uint64,proto3,oneof"`
}

type Range_Timestamp struct {
	Timestamp *TimestampRange `protobuf:"bytes,20,opt,name=timestamp,proto3,oneof"`
}

type Range_Date struct {
	Date *DateRange `protobuf:"bytes,21,opt,name=date,proto3,oneof"`
}

func (*Range_Double) isRange_Type() {}

func (*Range_Fixed32) isRange_Type() {}

func (*Range_Fixed64) isRange_Type() {}

func (*Range_Float) isRange_Type() {}

func (*Range_Int32) isRange_Type() {}

func (*Range_Int64) isRange_Type() {}

func (*Range_Sfixed32) isRange_Type() {}

func (*Range_Sfixed64) isRange_Type() {}

func (*Range_Sint32) isRange_Type() {}

func (*Range_Sint64) isRange_Type() {}

func (*Range_Uint32) isRange_Type() {}

func (*Range_Uint64) isRange_Type() {}

func (*Range_Timestamp) isRange_Type() {}

func (*Range_Date) isRange_Type() {}

type DoubleRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min float64 `protobuf:"fixed64,1,opt,name=min,proto3" json:"min,omitempty"`
	Max float64 `protobuf:"fixed64,2,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *DoubleRange) Reset() {
	*x = DoubleRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_fields_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoubleRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleRange) ProtoMessage() {}

func (x *DoubleRange) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_fields_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleRange.ProtoReflect.Descriptor instead.
func (*DoubleRange) Descriptor() ([]byte, []int) {
	return file_listify_v1_fields_proto_rawDescGZIP(), []int{5}
}

func (x *DoubleRange) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *DoubleRange) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type Fixed32Range struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min uint32 `protobuf:"fixed32,1,opt,name=min,proto3" json:"min,omitempty"`
	Max uint32 `protobuf:"fixed32,2,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *Fixed32Range) Reset() {
	*x = Fixed32Range{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_fields_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fixed32Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fixed32Range) ProtoMessage() {}

func (x *Fixed32Range) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_fields_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fixed32Range.ProtoReflect.Descriptor instead.
func (*Fixed32Range) Descriptor() ([]byte, []int) {
	return file_listify_v1_fields_proto_rawDescGZIP(), []int{6}
}

func (x *Fixed32Range) GetMin() uint32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Fixed32Range) GetMax() uint32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type Fixed64Range struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min uint64 `protobuf:"fixed64,1,opt,name=min,proto3" json:"min,omitempty"`
	Max uint64 `protobuf:"fixed64,2,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *Fixed64Range) Reset() {
	*x = Fixed64Range{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_fields_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fixed64Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fixed64Range) ProtoMessage() {}

func (x *Fixed64Range) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_fields_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fixed64Range.ProtoReflect.Descriptor instead.
func (*Fixed64Range) Descriptor() ([]byte, []int) {
	return file_listify_v1_fields_proto_rawDescGZIP(), []int{7}
}

func (x *Fixed64Range) GetMin() uint64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Fixed64Range) GetMax() uint64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type FloatRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min float32 `protobuf:"fixed32,1,opt,name=min,proto3" json:"min,omitempty"`
	Max float32 `protobuf:"fixed32,2,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *FloatRange) Reset() {
	*x = FloatRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_fields_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FloatRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatRange) ProtoMessage() {}

func (x *FloatRange) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_fields_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatRange.ProtoReflect.Descriptor instead.
func (*FloatRange) Descriptor() ([]byte, []int) {
	return file_listify_v1_fields_proto_rawDescGZIP(), []int{8}
}

func (x *FloatRange) GetMin() float32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *FloatRange) GetMax() float32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type Int32Range struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min int32 `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max int32 `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *Int32Range) Reset() {
	*x = Int32Range{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_fields_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int32Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32Range) ProtoMessage() {}

func (x *Int32Range) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_fields_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32Range.ProtoReflect.Descriptor instead.
func (*Int32Range) Descriptor() ([]byte, []int) {
	return file_listify_v1_fields_proto_rawDescGZIP(), []int{9}
}

func (x *Int32Range) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Int32Range) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type Int64Range struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min int64 `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max int64 `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *Int64Range) Reset() {
	*x = Int64Range{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_fields_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int64Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int64Range) ProtoMessage() {}

func (x *Int64Range) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_fields_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int64Range.ProtoReflect.Descriptor instead.
func (*Int64Range) Descriptor() ([]byte, []int) {
	return file_listify_v1_fields_proto_rawDescGZIP(), []int{10}
}

func (x *Int64Range) GetMin() int64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Int64Range) GetMax() int64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type SFixed32Range struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min int32 `protobuf:"fixed32,1,opt,name=min,proto3" json:"min,omitempty"`
	Max int32 `protobuf:"fixed32,2,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *SFixed32Range) Reset() {
	*x = SFixed32Range{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_fields_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SFixed32Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SFixed32Range) ProtoMessage() {}

func (x *SFixed32Range) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_fields_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SFixed32Range.ProtoReflect.Descriptor instead.
func (*SFixed32Range) Descriptor() ([]byte, []int) {
	return file_listify_v1_fields_proto_rawDescGZIP(), []int{11}
}

func (x *SFixed32Range) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *SFixed32Range) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type SFixed64Range struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min int64 `protobuf:"fixed64,1,opt,name=min,proto3" json:"min,omitempty"`
	Max int64 `protobuf:"fixed64,2,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *SFixed64Range) Reset() {
	*x = SFixed64Range{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_fields_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SFixed64Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SFixed64Range) ProtoMessage() {}

func (x *SFixed64Range) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_fields_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SFixed64Range.ProtoReflect.Descriptor instead.
func (*SFixed64Range) Descriptor() ([]byte, []int) {
	return file_listify_v1_fields_proto_rawDescGZIP(), []int{12}
}

func (x *SFixed64Range) GetMin() int64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *SFixed64Range) GetMax() int64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type SInt32Range struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min int32 `protobuf:"zigzag32,1,opt,name=min,proto3" json:"min,omitempty"`
	Max int32 `protobuf:"zigzag32,2,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *SInt32Range) Reset() {
	*x = SInt32Range{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_fields_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SInt32Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SInt32Range) ProtoMessage() {}

func (x *SInt32Range) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_fields_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SInt32Range.ProtoReflect.Descriptor instead.
func (*SInt32Range) Descriptor() ([]byte, []int) {
	return file_listify_v1_fields_proto_rawDescGZIP(), []int{13}
}

func (x *SInt32Range) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *SInt32Range) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type SInt64Range struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min int64 `protobuf:"zigzag64,1,opt,name=min,proto3" json:"min,omitempty"`
	Max int64 `protobuf:"zigzag64,2,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *SInt64Range) Reset() {
	*x = SInt64Range{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_fields_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SInt64Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SInt64Range) ProtoMessage() {}

func (x *SInt64Range) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_fields_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SInt64Range.ProtoReflect.Descriptor instead.
func (*SInt64Range) Descriptor() ([]byte, []int) {
	return file_listify_v1_fields_proto_rawDescGZIP(), []int{14}
}

func (x *SInt64Range) GetMin() int64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *SInt64Range) GetMax() int64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type UInt32Range struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min uint32 `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max uint32 `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *UInt32Range) Reset() {
	*x = UInt32Range{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_fields_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UInt32Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UInt32Range) ProtoMessage() {}

func (x *UInt32Range) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_fields_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UInt32Range.ProtoReflect.Descriptor instead.
func (*UInt32Range) Descriptor() ([]byte, []int) {
	return file_listify_v1_fields_proto_rawDescGZIP(), []int{15}
}

func (x *UInt32Range) GetMin() uint32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *UInt32Range) GetMax() uint32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type UInt64Range struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min uint64 `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max uint64 `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *UInt64Range) Reset() {
	*x = UInt64Range{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_fields_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UInt64Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UInt64Range) ProtoMessage() {}

func (x *UInt64Range) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_fields_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UInt64Range.ProtoReflect.Descriptor instead.
func (*UInt64Range) Descriptor() ([]byte, []int) {
	return file_listify_v1_fields_proto_rawDescGZIP(), []int{16}
}

func (x *UInt64Range) GetMin() uint64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *UInt64Range) GetMax() uint64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type TimestampRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=min,proto3" json:"min,omitempty"`
	Max *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *TimestampRange) Reset() {
	*x = TimestampRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_fields_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimestampRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampRange) ProtoMessage() {}

func (x *TimestampRange) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_fields_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampRange.ProtoReflect.Descriptor instead.
func (*TimestampRange) Descriptor() ([]byte, []int) {
	return file_listify_v1_fields_proto_rawDescGZIP(), []int{17}
}

func (x *TimestampRange) GetMin() *timestamppb.Timestamp {
	if x != nil {
		return x.Min
	}
	return nil
}

func (x *TimestampRange) GetMax() *timestamppb.Timestamp {
	if x != nil {
		return x.Max
	}
	return nil
}

type DateRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Valid values for min are: YYYY, YYYY-MM, or YYYY-MM-DD
	Min string `protobuf:"bytes,1,opt,name=min,proto3" json:"min,omitempty"`
	// Valid values for max are: YYYY, YYYY-MM, or YYYY-MM-DD
	Max string `protobuf:"bytes,2,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *DateRange) Reset() {
	*x = DateRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listify_v1_fields_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DateRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateRange) ProtoMessage() {}

func (x *DateRange) ProtoReflect() protoreflect.Message {
	mi := &file_listify_v1_fields_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateRange.ProtoReflect.Descriptor instead.
func (*DateRange) Descriptor() ([]byte, []int) {
	return file_listify_v1_fields_proto_rawDescGZIP(), []int{18}
}

func (x *DateRange) GetMin() string {
	if x != nil {
		return x.Min
	}
	return ""
}

func (x *DateRange) GetMax() string {
	if x != nil {
		return x.Max
	}
	return ""
}

var File_listify_v1_fields_proto protoreflect.FileDescriptor

var file_listify_v1_fields_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x69,
	0x66, 0x79, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x67, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x78, 0x74, 0x5f,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x65, 0x78, 0x74,
	0x50, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x70, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x50,
	0x61, 0x67, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x1e, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x3c, 0x0a, 0x04, 0x53, 0x6f, 0x72, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x73, 0x63, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x64, 0x65, 0x73, 0x63,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x22, 0x76, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x16, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x29,
	0x0a, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x48, 0x00, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x13, 0x0a, 0x0c, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x03, 0xf8, 0x42, 0x01, 0x22, 0xea,
	0x05, 0x0a, 0x05, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x64, 0x6f, 0x75, 0x62,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69,
	0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x52, 0x61, 0x6e, 0x67,
	0x65, 0x48, 0x00, 0x52, 0x06, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x66,
	0x69, 0x78, 0x65, 0x64, 0x33, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c,
	0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x78, 0x65, 0x64, 0x33,
	0x32, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x07, 0x66, 0x69, 0x78, 0x65, 0x64, 0x33,
	0x32, 0x12, 0x34, 0x0a, 0x07, 0x66, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e,
	0x46, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x07,
	0x66, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x12, 0x2e, 0x0a, 0x05, 0x66, 0x6c, 0x6f, 0x61, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00,
	0x52, 0x05, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x2e, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x33, 0x32,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00,
	0x52, 0x05, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x2e, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x36, 0x34,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00,
	0x52, 0x05, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x37, 0x0a, 0x08, 0x73, 0x66, 0x69, 0x78, 0x65,
	0x64, 0x33, 0x32, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x69, 0x73, 0x74,
	0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x46, 0x69, 0x78, 0x65, 0x64, 0x33, 0x32, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x08, 0x73, 0x66, 0x69, 0x78, 0x65, 0x64, 0x33, 0x32,
	0x12, 0x37, 0x0a, 0x08, 0x73, 0x66, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x46, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52,
	0x08, 0x73, 0x66, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x69, 0x6e,
	0x74, 0x33, 0x32, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6c, 0x69, 0x73, 0x74,
	0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x48, 0x00, 0x52, 0x06, 0x73, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x31, 0x0a, 0x06,
	0x73, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6c,
	0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x49, 0x6e, 0x74, 0x36, 0x34,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x06, 0x73, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12,
	0x31, 0x0a, 0x06, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x49, 0x6e,
	0x74, 0x33, 0x32, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x06, 0x75, 0x69, 0x6e, 0x74,
	0x33, 0x32, 0x12, 0x31, 0x0a, 0x06, 0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x06, 0x75,
	0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x3a, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69,
	0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x15, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x74,
	0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x42, 0x0b,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x03, 0xf8, 0x42, 0x01, 0x22, 0x31, 0x0a, 0x0b, 0x44,
	0x6f, 0x75, 0x62, 0x6c, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0x32,
	0x0a, 0x0c, 0x46, 0x69, 0x78, 0x65, 0x64, 0x33, 0x32, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52, 0x03, 0x6d, 0x69, 0x6e,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x07, 0x52, 0x03, 0x6d,
	0x61, 0x78, 0x22, 0x32, 0x0a, 0x0c, 0x46, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52,
	0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x06, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0x30, 0x0a, 0x0a, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0x30, 0x0a, 0x0a, 0x49, 0x6e, 0x74, 0x33,
	0x32, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0x30, 0x0a, 0x0a, 0x49, 0x6e,
	0x74, 0x36, 0x34, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0x33, 0x0a, 0x0d,
	0x53, 0x46, 0x69, 0x78, 0x65, 0x64, 0x33, 0x32, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0f, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0f, 0x52, 0x03, 0x6d, 0x61,
	0x78, 0x22, 0x33, 0x0a, 0x0d, 0x53, 0x46, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x10, 0x52,
	0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x10, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0x31, 0x0a, 0x0b, 0x53, 0x49, 0x6e, 0x74, 0x33, 0x32,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x11, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x11, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0x31, 0x0a, 0x0b, 0x53, 0x49, 0x6e,
	0x74, 0x36, 0x34, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x12, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x12, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0x31, 0x0a, 0x0b,
	0x55, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22,
	0x31, 0x0a, 0x0b, 0x55, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6d, 0x69, 0x6e,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6d,
	0x61, 0x78, 0x22, 0x6c, 0x0a, 0x0e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x12, 0x2c, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x03, 0x6d,
	0x69, 0x6e, 0x12, 0x2c, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x03, 0x6d, 0x61, 0x78,
	0x22, 0x89, 0x01, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x3d,
	0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x2b, 0xfa, 0x42, 0x28,
	0x72, 0x26, 0x32, 0x24, 0x28, 0x5b, 0x30, 0x2d, 0x39, 0x5d, 0x7b, 0x34, 0x7d, 0x2d, 0x3f, 0x28,
	0x5b, 0x30, 0x2d, 0x39, 0x5d, 0x7b, 0x32, 0x7d, 0x29, 0x3f, 0x2d, 0x3f, 0x28, 0x5b, 0x30, 0x2d,
	0x39, 0x5d, 0x7b, 0x32, 0x7d, 0x29, 0x3f, 0x29, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x3d, 0x0a,
	0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x2b, 0xfa, 0x42, 0x28, 0x72,
	0x26, 0x32, 0x24, 0x28, 0x5b, 0x30, 0x2d, 0x39, 0x5d, 0x7b, 0x34, 0x7d, 0x2d, 0x3f, 0x28, 0x5b,
	0x30, 0x2d, 0x39, 0x5d, 0x7b, 0x32, 0x7d, 0x29, 0x3f, 0x2d, 0x3f, 0x28, 0x5b, 0x30, 0x2d, 0x39,
	0x5d, 0x7b, 0x32, 0x7d, 0x29, 0x3f, 0x29, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x42, 0x3a, 0x5a, 0x38,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x65, 0x6e, 0x74, 0x6f,
	0x70, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x6c, 0x69,
	0x73, 0x74, 0x69, 0x66, 0x79, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x2f, 0x76, 0x31,
	0x3b, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x66, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_listify_v1_fields_proto_rawDescOnce sync.Once
	file_listify_v1_fields_proto_rawDescData = file_listify_v1_fields_proto_rawDesc
)

func file_listify_v1_fields_proto_rawDescGZIP() []byte {
	file_listify_v1_fields_proto_rawDescOnce.Do(func() {
		file_listify_v1_fields_proto_rawDescData = protoimpl.X.CompressGZIP(file_listify_v1_fields_proto_rawDescData)
	})
	return file_listify_v1_fields_proto_rawDescData
}

var file_listify_v1_fields_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_listify_v1_fields_proto_goTypes = []interface{}{
	(*Page)(nil),                  // 0: listify.v1.Page
	(*Search)(nil),                // 1: listify.v1.Search
	(*Sort)(nil),                  // 2: listify.v1.Sort
	(*Filter)(nil),                // 3: listify.v1.Filter
	(*Range)(nil),                 // 4: listify.v1.Range
	(*DoubleRange)(nil),           // 5: listify.v1.DoubleRange
	(*Fixed32Range)(nil),          // 6: listify.v1.Fixed32Range
	(*Fixed64Range)(nil),          // 7: listify.v1.Fixed64Range
	(*FloatRange)(nil),            // 8: listify.v1.FloatRange
	(*Int32Range)(nil),            // 9: listify.v1.Int32Range
	(*Int64Range)(nil),            // 10: listify.v1.Int64Range
	(*SFixed32Range)(nil),         // 11: listify.v1.SFixed32Range
	(*SFixed64Range)(nil),         // 12: listify.v1.SFixed64Range
	(*SInt32Range)(nil),           // 13: listify.v1.SInt32Range
	(*SInt64Range)(nil),           // 14: listify.v1.SInt64Range
	(*UInt32Range)(nil),           // 15: listify.v1.UInt32Range
	(*UInt64Range)(nil),           // 16: listify.v1.UInt64Range
	(*TimestampRange)(nil),        // 17: listify.v1.TimestampRange
	(*DateRange)(nil),             // 18: listify.v1.DateRange
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
}
var file_listify_v1_fields_proto_depIdxs = []int32{
	4,  // 0: listify.v1.Filter.range:type_name -> listify.v1.Range
	5,  // 1: listify.v1.Range.double:type_name -> listify.v1.DoubleRange
	6,  // 2: listify.v1.Range.fixed32:type_name -> listify.v1.Fixed32Range
	7,  // 3: listify.v1.Range.fixed64:type_name -> listify.v1.Fixed64Range
	8,  // 4: listify.v1.Range.float:type_name -> listify.v1.FloatRange
	9,  // 5: listify.v1.Range.int32:type_name -> listify.v1.Int32Range
	10, // 6: listify.v1.Range.int64:type_name -> listify.v1.Int64Range
	11, // 7: listify.v1.Range.sfixed32:type_name -> listify.v1.SFixed32Range
	12, // 8: listify.v1.Range.sfixed64:type_name -> listify.v1.SFixed64Range
	13, // 9: listify.v1.Range.sint32:type_name -> listify.v1.SInt32Range
	14, // 10: listify.v1.Range.sint64:type_name -> listify.v1.SInt64Range
	15, // 11: listify.v1.Range.uint32:type_name -> listify.v1.UInt32Range
	16, // 12: listify.v1.Range.uint64:type_name -> listify.v1.UInt64Range
	17, // 13: listify.v1.Range.timestamp:type_name -> listify.v1.TimestampRange
	18, // 14: listify.v1.Range.date:type_name -> listify.v1.DateRange
	19, // 15: listify.v1.TimestampRange.min:type_name -> google.protobuf.Timestamp
	19, // 16: listify.v1.TimestampRange.max:type_name -> google.protobuf.Timestamp
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_listify_v1_fields_proto_init() }
func file_listify_v1_fields_proto_init() {
	if File_listify_v1_fields_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_listify_v1_fields_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Page); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_fields_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Search); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_fields_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_fields_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_fields_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Range); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_fields_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoubleRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_fields_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fixed32Range); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_fields_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fixed64Range); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_fields_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FloatRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_fields_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Int32Range); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_fields_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Int64Range); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_fields_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SFixed32Range); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_fields_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SFixed64Range); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_fields_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SInt32Range); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_fields_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SInt64Range); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_fields_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UInt32Range); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_fields_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UInt64Range); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_fields_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimestampRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listify_v1_fields_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DateRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_listify_v1_fields_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*Filter_Value)(nil),
		(*Filter_Range)(nil),
	}
	file_listify_v1_fields_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*Range_Double)(nil),
		(*Range_Fixed32)(nil),
		(*Range_Fixed64)(nil),
		(*Range_Float)(nil),
		(*Range_Int32)(nil),
		(*Range_Int64)(nil),
		(*Range_Sfixed32)(nil),
		(*Range_Sfixed64)(nil),
		(*Range_Sint32)(nil),
		(*Range_Sint64)(nil),
		(*Range_Uint32)(nil),
		(*Range_Uint64)(nil),
		(*Range_Timestamp)(nil),
		(*Range_Date)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_listify_v1_fields_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_listify_v1_fields_proto_goTypes,
		DependencyIndexes: file_listify_v1_fields_proto_depIdxs,
		MessageInfos:      file_listify_v1_fields_proto_msgTypes,
	}.Build()
	File_listify_v1_fields_proto = out.File
	file_listify_v1_fields_proto_rawDesc = nil
	file_listify_v1_fields_proto_goTypes = nil
	file_listify_v1_fields_proto_depIdxs = nil
}
